### ISSUE TITLE
HYGEN_OVERWRITE value 1 and 0

### ISSUE THREAD

**Issue by mcflythekid** [jondot/hygen#113]
Hi,
I need to pass value to HYGEN_OVERWRITE environment variable.

Now I see that the code does not check value for HYGEN_OVERWRITE
Instead, It just check if the HYGEN_OVERWRITE is exists and force overwrite

**Comment by Alebat** [comment]
I prefer doing this via command line, to be cross-compatible (bash, cmd, Powershell):
`echo yyy | hygen my-generator new`
The problem is that you have to know how many files you may overwrite a proiri.

**Comment by jondot** [comment]
@mcflythekid yes, there is no meaning for whats inside HYGEN_OVERWRITE, because it's a "yes, overwrite, or no - prompt". What values did you expect?

@Alebat do you know [cross-env](https://www.npmjs.com/package/cross-env)?
