### ISSUE TITLE
Empty line after genarated injection

### ISSUE THREAD

**Issue by goschevski** [jondot/hygen#114]
Hi,

I couldn't find this in documentation... Is it possible to prevent adding blank line after injection.

Use case:

routes.js
```
// controllers
const usersController = require('./controllers/users');
const articlesController = require('./controllers/articles');
```
generator
```
---
to: server/routes.js
inject: true
skip_if: "./controllers/<%= controller %>"
after: "// controllers"
---
const <%= controller %>Controller = require('./controllers/<%= controller %>');
```

I want my controller to be required in one paragraph.
If this is not supported, I would suggest something like `emptyLineAfter: true|false`

**Comment by anithri** [comment]
It's because there's a blank line at the end of your file and hygen is installing it.  If you remove that blank line, it won't end up in in the file.

**Comment by goschevski** [comment]
Nope, that's not the case... I don't have empty line at the end of the file.

**Comment by jondot** [comment]
Will check, thanks!
