### ISSUE TITLE
How to embed in cli tool

### ISSUE THREAD

**Issue by itainoam** [jondot/hygen#118]
Hi there!

Great job. Really useful tool. I love how easy it is to add new templates/generators.

I would like wrap it in a CLI tool to provide autocomplete and other customization. I saw that you provided example, but can you expand a little?

```
const { runner } = require('hygen')
const Logger = require('hygen/lib/logger')
const path = require('path')
const defaultTemplates = path.join(__dirname, 'templates')

runner(process.argv.slice(2), {
  templates: defaultTemplates,
  cwd: process.cwd(),
  logger: new Logger(console.log.bind(console)),
  createPrompter: () => require('enquirer'),
  exec: (action, body) => {
    const opts = body && body.length > 0 ? { input: body } : {}
    return require('execa').shell(action, opts)
  },
  debug: !!process.env.DEBUG
})
```

Can you expand a little on the how that works. What's `createPrompter` and `exec`?

**Comment by jondot** [comment]
Hi,
You can find a working example here: https://github.com/jondot/dazzling/blob/master/packages/dazzling-core/bin.js

`createPrompter` is an abstraction, in which you can supply a different prompting library (currently the two that are compatible are `enquirer` and `inquirer`.

`exec` is an abstraction around shell executing templates/actions, where you can supply a different library for executing or drive your own concerns (such as allowing/disallowing only certain shell commands etc.)

**Comment by itainoam** [comment]
Thanks for the quick answer. No sure I completely understand.

Maybe I'll dive a little into my use case.
I'm trying to prompt the user for a singular name and then suggest a plural but allow override.

`
> Singular Name?                                          "person list"
> Plural Name (default: person lists)?         "people lists"
`

**Comment by jondot** [comment]
Just a step back, are you trying to embed Hygen or just use it?
To be clear, embedding Hygen means you want to build an executable that uses Hygen internally as its generator engine.
If you have your project somewhere, I can take a look and see how I can help.

**Comment by itainoam** [comment]
So I figured it out. Turns out `inquirer` has everything you need. No need to embed in external tool.

I think that [area](http://www.hygen.io/generators#advanced-params) in the documentation can be further clarified. If you'd like I can give it a try.

**Comment by jondot** [comment]
Happy you found a solution!
Sure of course, docs can also use more love, I'll happily accept your PR
