### ISSUE TITLE
hygen example-prompt new

### ISSUE THREAD

**Issue by agung-wete** [jondot/hygen#12]
**cat** is not windows OS compatible
https://github.com/jondot/hygen/blob/95d8742bf2f6f633330efad821292efc44ffe88a/src/templates/example/new/shell.ejs.t#L2

**Comment by jondot** [comment]
sorry about that. any cross platform tool you can think of that does the same?

**Comment by agung-wete** [comment]
https://www.appveyor.com/docs/lang/nodejs-iojs/ maybe
