### ISSUE TITLE
Run code inside the template

### ISSUE THREAD

**Issue by kfrajtak** [jondot/hygen#123]
Hi,
I'd like to generate code based on JSON schema file. Is it possible to create a `hygen` generator template that will run `node` inside it? In this case it will open the file, process it and generate the output, a functionality similar to example of [T4 engine](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019).

```
<#@ output extension=".cs" #>
<#@ assembly name="System.Xml" #>
<#
 System.Xml.XmlDocument configurationData = ...; // Read a data file here. 
#>
namespace Fabrikam.<#= configurationData.SelectSingleNode("jobName").Value #>
{
  ... // More code here.
}
```

Thanks,
Karel

**Comment by anithri** [comment]
Not exactly like that, but it can be done.  [See the docs](http://www.hygen.io/generators#advanced-params)

```javascript
// app/_templates/generator/action/index.js
const fs = require('fs')
module.exports = {
params: ({args}) => {
  // use fs (or similar) to read data
  // process data
  // add to args

  // anything you add to args available in templates
  args.thing = 'chair'
  
  args.imports = {fs: 'fs', react: 'react', Header: 'components/header'}
  args.allImports = Object.entries(imports).map(([var, path]) =>  `import ${var} from '${path}`)
  return args
}
```
```ejs
// app/_templates/generator/action/thing.ejs.t
---
to: somewhere
---
<%- allImports %>
// or
<% Object.entries(imports).forEach(function ([var,path])  { %>
  import <%- var %> from '<%- path %>'
<% }) %>

It's a <%- thing %>!

```

After that's it's just figuring out how to use the data you got.  I've found that sometimes it's easier to generate display text in the params function to display directly instead of looping and conditionals in the template itself. But that's just my preference.

**Comment by jondot** [comment]
❤️
