### ISSUE TITLE
bug: when providing a boolean parameter and defining a prompt, when parameter is falsy, the prompt still requests inpu

### ISSUE THREAD

**Issue by rantav** [jondot/hygen#129]
Here's the scenario, bare with me... 
We have a boolean parameter `include_grpc` so we can invoke hygen with either 

	hygen template init my-project --include_grpc=1

or

	hygen template init my-project --include_grpc=0

This works well in the sense that `include_grpc` is assigned the proper boolean value. 

OK. 
Now we add a prompt to prompts.js: 

    {
      type: 'toggle',
      name: 'include_grpc',
      message: "Include gRPC functionality in this project? (proto file, client, server)"
    },

And running: 

	hygen template init my-project   

(not specifying a value for `--include_grpc`) then we're fine - the prompt gets triggered and I'm asked wether I'd like to add grpc or not.  
Works as expected, cool. 

When running:

	hygen template init my-project --include_grpc=1

That also works as expected, the prompt isn't triggered b/c the value was already provided

However, when running 

	hygen template init my-project --include_grpc=0

The prompt **is triggered** even though the value was specified to be 0/false. 
That's a bug. 

Just a guess: you probably need to check for nullity rather than truthy/falsy values when determining whether to invoke the prompt.

**Comment by jondot** [comment]
yeap. will fix!
