### ISSUE TITLE
Don't Prompt if Variable is on CLI

### ISSUE THREAD

**Issue by scramblor** [jondot/hygen#132]
It would be nice if Hygen would not prompt for variables if I have included them on the CLI.

Looking at src/prompt.js it seems this functionality is already written. However it does not exist on lib/prompt.js which is what is actually run. Is this mismatch intentional or is something not working in the build pipeline?

**Comment by jondot** [comment]
interesting. no i believe it may be something in the build. i'll run a new one.

**Comment by jondot** [comment]
new build is out, feel free to check out the new version and thanks!

**Comment by scramblor** [comment]
Working now! Thanks for the quick fix.
