### ISSUE TITLE
Support folders in gen:action folder

### ISSUE THREAD

**Issue by milesj** [jondot/hygen#133]
At the moment, it seems like all templates need to be in the root of the action folder. It would be nice to support nested folders so something like this is possible.

<img width="265" alt="Screen Shot 2019-08-05 at 19 49 54" src="https://user-images.githubusercontent.com/143744/62507793-5044d880-b7ba-11e9-8819-f062ebebc025.png">

**Comment by anithri** [comment]
#102

**Comment by jondot** [comment]
🚀
