### ISSUE TITLE
[ADVICE] Looking for suggestions for running generators for testing

### ISSUE THREAD

**Issue by AshleyColemanBigHealth** [jondot/hygen#134]
I would love to be able to "flick a switch", and redirect the file operations _somewhere_ for the purposes of testing. e.g.

1. append `"test/"` to every frontmatter `to`, or
1. dry-run, but log file operations

If not, I might modifyi every frontmatter `to`:
```log
------------------------------------------
to: <%= test ? './test_tmp' : null %>/src/..
------------------------------------------
```
and then running generator in "test mode"
```sh
hygen component new Button --test
```

Is there any options I should consider?

Thanks!

**Comment by anithri** [comment]
`--dry`

**Comment by AshleyColemanBigHealth** [comment]
Ah so it turns out `--dry` does not show the _actual_ delta being applied to files. Only the standard output (names of files being changes). I'll add a test mode to my frontmatter

**Comment by jondot** [comment]
@AshleyColemanBigHealth interesting, what if you add a function called `app` or something similar to your `hygen.js` file (which makes it available on all templates) and then use `<%= app() %>/foo/bar`.

What `app()` will do is give you the path in "test" mode and in "dev" mode, lets say:

```
const app = ()=>process.env["TEST"] ? 'test' : 'app'
```

and then:

```
$ TEST=true hygen foo bar..
```

Will that work?
