### ISSUE TITLE
Reusing Templates

### ISSUE THREAD

**Issue by donaldtf** [jondot/hygen#137]
I am curious if it is possible to reuse templates in multiple generators? My use case involves a monorepo built using lerna. I created a generator to create new learna packages and it is working like a charm. The packages in this lerna repo will all contain collections of react components, so I populate the lerna package with a default component. I want to reuse templates because I am imagining a scenario like this:

1. I generate a new package via hygen with a basic component in it. I start working on that basic component
2. I realize that basic component needs another sub component inside of it. I reach for hygen to generate that new component as well.

I would like for the lerna package generator and component generator to share the same basic template for my react components. I could create another generator, but then I would have to manage multiple identical templates. I think I could maybe finagle something together by using the conditional rendering described [here](http://www.hygen.io/templates/#conditional-rendering), but reusing templates feels like it would be a more elegant solution. Any suggestions?

**Comment by anithri** [comment]
I haven't done this yet, but here's the approach I'm considering.
`_templates/lib/shared_a` exists as a generator/action
```
//  _templates/mygen/action/shared
---
sh: hygen lib shared_a --name dest/path
---
```

**Comment by donaldtf** [comment]
@anithri Just finally had a chance to try your suggestion and it works like a charm! Thanks!

**Comment by danielo515** [comment]
Even if the suggestion of @anithri works, I still thinks this is a common thing and can be a feature to add.

**Comment by danielo515** [comment]
Just read the docs and found this:
http://www.hygen.io/docs/templates#from--shared-templates
so it is already supported, cool!

**Comment by danielo515** [comment]
Ok, my bad, the from only allows you to copy the template as it is, it dos not parse and apply the variables, so it is not useful on this scenario.
