### ISSUE TITLE
bug: 'eof_last: false' breaks generation

### ISSUE THREAD

**Issue by mprast** [jondot/hygen#146]
Hi all,
   I'm having issues with `eof_last` (which I'm unsure is still supported? It looks like it's still in source and I see it referenced in the README, but it's not anywhere in the hygen.io docs and nobody brought it up in https://github.com/jondot/hygen/issues/114). 

I have a generator called package/new. There are several add templates in there, and there's also this inject template:

```
---
inject: true
to: tsconfig.json
after: references
skip_if: <%= packageName %>
---
    {"path": "./packages/<%= packageName %>"},
```

Like goschevski in #114, I've confirmed that there's no newline at the end of the file and am still seeing newlines injected into my tsconfig. To fix this I tried adding `eof_last: false` to the end of the frontmatter.

After making this change, I expected the injector to run as before, inserting the provided line into my tsconfig w\ no trailing newline. Instead, I got several different results, depending on where `eof_last` was in the frontmatter:

-If `eof_last` was at the very end of the frontmatter, hygen would process the add templates as normal, but would ignore the inject one (i.e. the `inject: tsconfig.json` line would be missing from the output). I confirmed the `skip_if` pattern was not present in .tsconfig, and confirmed that the injector did indeed run if I took out the `eof_last` line.

-If `eof_last` was anywhere else, it would appear to break attribute parsing, and hygen wouldn't process any templates. I'd get the message 
`TypeError: Cannot create property '<next_property_name>' on boolean 'false'`. Here `<next_property_name>` is the name of the property immediately after `eof_last` - so if `eof_last` was on the second to last line, it'd be `skip_if`.

^^the behavior above persisted even when I added manually added a newline to my inject template. I tried setting `eof_last` to `true` and had no issues - hygen injected a single newline after the template contents (so, in fact, I got the same results when setting `eof_last` to `true` as I got from excluding `eof_last` altogether). 

Please let me know if there's any other context I can give. Thanks!

**Comment by jondot** [comment]
@mprast any chance you can point me to the repo you have the templates in? that would be really helpful

**Comment by mprast** [comment]
@jondot yes! the template in question is at https://github.com/mprast/atlas/blob/master/global_templates/package/new/root_tsconfig.json.ejs

**Comment by noemission** [comment]
I think it's related to #165

**Comment by jondot** [comment]
closing since looks like its resolved
