### ISSUE TITLE
Non-monospace font used in code blocks in docs

### ISSUE THREAD

**Issue by LachlanArthur** [jondot/hygen#15]
The code blocks in the docs use variants of `Lucida Sans` on Windows, which is not a monospace font.

This makes the ASCII art a little confusing:
![Screenshot](https://user-images.githubusercontent.com/1870204/36080977-54ecbf12-0fe4-11e8-841d-165a3244dda3.png)

You probably want `Lucida Console` instead.

**Comment by jondot** [comment]
Thanks for letting me know! I'll make sure we're using a monospace font for Windows too

**Comment by jondot** [comment]
Should be good now, thanks!
