### ISSUE TITLE
use hygen as a node module?

### ISSUE THREAD

**Issue by jrobinson01** [jondot/hygen#155]
Is it possible to use hygen as a node module? I'm currently working on an npm script to generate a bunch of icon components. It works well enough, but it's rather slow. Here's what I'm currently doing:

```javascript
// generate icons
icons.forEach(async icon => {
  // generate the template with hygen
  try {
    await execa('hygen' ,[my-icon', 'new', icon.name, `--svg=${icon.contents}`]);
  } catch(e) {
    console.error('error generating icon:', e);
  }
});
```
I'd rather not have to use `execa` (aka, spawn) if avoidable (I'm not 100% sure that's where my bottleneck is, but I assume it's not helping).

**Comment by anithri** [comment]
Interesting, but I'm having a hard time understanding how you are going to use this, so I have questions.
1. Is this a one time generation or will it be reused again and again?
2. Where is that snippet being executed from?  Inside hygen (hygen.js, index.js, prompt.js) or outside.
3. How complicated is the `_templates/my-icon/new/icon.ejs.t` file?
4. How many icons are we talking, and how stable is that number?

There's got to be a better answer than that example, but it depends a lot on the answers.

The snippet, while thorough, is about the slowest way you can do it involving hygen.  The catch is that hygen isn't (yet) setup to do what would optimize the solution by having the ability to add more templates to generate, or to reuse the same template with multiple set of data. 

There are several ways to sidestep the problem, mostly centering around `_templates/generator/action/[index,prompt].js` or `project/.hygen.js` files.

**Comment by jrobinson01** [comment]
1. It will be used infrequently. I use it when new icons (.svg files) are added to the collection, or they've been modified.

2. The snippet executes inside a node script, triggered as an npm script.

3. The icon template isn't overly complicated. I could probably just not use hygen at all and achieve the same result pretty easily. I started with the idea to use hygen and pushed forth until I had something working.

4. There are about 350 icons. The number will probably stay about the same, maybe going up a little here and there. 

I started the project thinking it'd be great to use hygen (somehow thinking I'd use it as a module inside node). I really like the templating system and like that I can change my template if needed and not have to muck around in the script itself. I'm definitely interested in any ways to sidestep the problem. I haven't dug at all into the more advanced usages of hygen. I've only ever created "new" type generators so far.

**Comment by anithri** [comment]
I think this should be a good use of hygen, we just need to tweak things to make it work.

getting the data into the hygen pipeline is easy, use `.hygen.js`, import the data, export the data in helpers.

create a generator action that creates a `icon-name.svg.ejs.t` with the template you wish your icon to use.
```
---
define: icon<% icon = h.icons.icon %>
to: icons/<%- icon.name %>.svg
---
// stuff
<%- icon.svg %>
///...
```

**Comment by anithri** [comment]
But maybe there should be an easier way of generating a set of files from a single template.
```ejs
---
vector: true
# generate template once for each element of the vectors array.
#   in pseudo code: vectors.forEach(v => render({...vector: v})) 
to: <%- vector.path %>
---
name: <%- vector.name %>
age: <%- vector.name %>
```

**Comment by jrobinson01** [comment]
I don't quite follow. After sleeping on it... what I need is a transform that can work in bulk. I have a folder full of *.svg files and want to transform each one into a folder full of .js files. In short, I don't understand how/where the loop comes into play.

**Comment by anithri** [comment]
My apologies for the miscommunication, my thoughts about `vector` were just ideas for adding the functionality to hygen.

easiest way to improve performance might be (please please check syntax before using any of this)
```javascript
jobs = icons.map(icon => Promise.new((resolve, reject) => {
  execa('hygen' ,[my-icon', 'new', icon.name, `--svg=${icon.contents}`])
  .catch(e) { console.error('error generating icon:', e); }
});

Promise.all(jobs).then( () => console.log(finished))
```

**Comment by jrobinson01** [comment]
For now it's working as is, it just takes about 15-20 seconds to finish. That's probably fine though since this job will run so infrequently. I think honestly, if there was a way to use hygen as a module it would speed things up quite a bit. I'm pretty sure I'm spinning up a new shell for each icon which is where my bottleneck is. I'd be interested in exploring how to use hygen directly in node. I'm not familiar at all with the code base though so that may take some time to experiment.

**Comment by jondot** [comment]
Hygen was built to be first-class embeddable, so yes, you can use it as a node module.
In our testing rig, we do that too.

Here is an example, you just need to complete the details of how you want to run hygen yourself:

```js
import { runner } from 'hygen'

const defaultTemplates = path.join(__dirname, '../src/templates')
runner(process.argv.slice(2), {
  templates: defaultTemplates,
  cwd: process.cwd(),
  logger: new Logger(console.log.bind(console)),
  debug: !!process.env.DEBUG,
  exec: (action, body) => {
    const opts = body && body.length > 0 ? { input: body } : {}
    return require('execa').command(action, { ...opts, shell: true })
  },
  createPrompter: () => require('enquirer'),
}).then(({ success }) => process.exit(success ? 0 : 1))
```
