### ISSUE TITLE
For which programming languages can hygen be used?

### ISSUE THREAD

**Issue by schittli** [jondot/hygen#156]
Good afternoon,
I was trying to figure out for which programming languages hygen was designed, but I was not able to find a clear overview.

Could you pease adjust the GitGub project description:
`The simple, fast, and scalable code generator that lives in your project.`
to something like this?:
`The simple, fast, and scalable code generator for JavaScript that lives in your project.`

This would help a lot to get started with hygen and 
to _not_ to reject it erroneously as 'probably inappropriate' :-)

Thanks a lot!, kind regards,
Thomas

**Comment by anithri** [comment]
It can generate any kind of text file.  The templating language uses javascript, but you don't have to use that.  I have templates setup for ruby classes, .eslintrc files, serverless framework config files, bash scripts, css, and even javascript.
