### ISSUE TITLE
Evolving templates

### ISSUE THREAD

**Issue by Tapppi** [jondot/hygen#16]
Hey, `hygen` is looking great, thanks for open-sourcing your work 🙂 

Have you yet thought about how to support evolving templates, or is that something you are not considering?

For example, suppose I have a generator `processor`, I use the template to create a bunch of processors with  `hygen processor new --name ex`. I then want to update all the rendered processors (for example to migrate all the processors to v2) to use a newer configuration parameter, what would be the `hygen` way of doing it.

I have though about this a little, and it seems that since hygen is very heavy on "convention over configuration" (which I love and preach by the way, both in internal and open-source projects!), one would make a new `V1toV2` migration in the generator, and simply put the new default in `new` (backing up V1 in `newV1` if it is needed). This migrator would basically be adding, replacing and removing the differences based on regexes like `skip_if` et cetera.

**Comment by jondot** [comment]
Hi! Thanks for the kind words, I hope Hygen is able to save you some time :)

The answer is yes, I've been through the rabbit hole for this. My answer is twofold:

**First, the bigger scope of this problem:**

I thought about versioning templates and then providing migration paths. It started with 'stamping' each generated file with metadata about the originating generator, and then trying to compute a migration path.

Half way through I felt I was implementing a version control system. In addition, I had to deal with cases where developer removed the 'stamp' or the changes to files were too fundamental to be migrated. As I went through this, it was just going into a rabbit hole that doesn't end.

So I concluded that this was too hard to Hygen to solve, and best to leave it to version control and tools like `jscodeshift` that understand the AST and code semantics.

**Lastly, the smaller (?) scope of this problem:**

What you're suggesting sounds easy enough but it will cover just parts of all of this story, but if you think it's good enough - I'm happy because that's validation for me 😎 . In practice it means to add an ability for a generator to _erase_ lines, which funnily enough I never needed to do - but I can schedule that into the roadmap!. 

If you want to do it _right now_ you can probably use a shell action, that runs `sed` or your preferred streaming text editor on the command line.

Hope this makes sense :)

**Comment by Tapppi** [comment]
> What you're suggesting sounds easy enough but it will cover just parts of all of this story, but if you think it's good enough - I'm happy because that's validation for me 😎 .

Yeah, the idea was to add a small generic feature that can be used to achieve this goal in a "dirty" way. I like the 80/20 rule, and this should solve 80% of our cases. It isn't pretty, and doesn't solve all the cases, but should work for most of them. 

One thought came up: how to indicate multiple lines that need to be replaced at different parts of file? If the block must be continuous, this is pretty much useless as a migration tool

> So I concluded that this was too hard for Hygen to solve, and best to leave it to version control and tools like jscodeshift that understand the AST and code semantics.

Yes for more complex cases (such as big framework transitions) [microgrammars](https://github.com/atomist/microgrammar) or AST transformations are more suitable. A higher level abstraction over such a framework could of course be possible, but quite hard and might not be worth the time 🙂

**Comment by jondot** [comment]
Hi!
By now, there has been contributed two things:

* A new pragma for the `add` operation, which only adds if a file doesn't exist.
* A new tool by @ronp001 called `hygen-create` which can automatically create generators from existing codebases

I believe a combination of those two should provide _some_ kind of path for migrations. WDYT?

**Comment by ronp001** [comment]
@Tapppi  - I'm experimenting with a git-based method for "reapplying" a new version of a generator on files that were created using an older version of that generator.  Is that in the general direction that you're looking for?  I'll gladly share if so.

**Comment by Tapppi** [comment]
@ronp001 Yes that is! Is there some regex support or does it not deal with customised patterns?

@jondot Those are great improvements! However, the main feature missing was regexes for replacement I think?

I am currently experimenting with other things, our partner company has a workflow that kind of addresses our problems. But this is still something I am looking for for my open-source projects.

**Comment by ronp001** [comment]
@Tapppi : no regex.  The idea is to use git in the following way:

Step 1:  make sure output of V1 of the generator is in a clean commit in git (I do a `git commit` or `git stash` before running the generator, and immediately `add` and `commit` the output)
```
A---B---C---D---E---F  master
    ^
    |
  clean output of generator V1 committed here (at B)
```
(note that commits C,D,E,F are based on the output of generator V1).

Step 2:  run generator V2 in a branch that is forked from the commit immediately preceding the commit of  generator V1 output (`temp branch #1`)
```
A---B---C---D---E---F  (master)
 \
  B'  (temp branch #1)
  ^
  |
 clean output of generator V2 committed here
```

Step 3: create another temporary branch off of master (`temp branch #2`)
```
A---B---C---D---E---F  (master, temp branch #2)
 \                  
  B'  (temp branch #1)
```

Step 4: rebase `temp branch #2` using the sequence of commits beginning right after the original generator (i.e., commit `C`) onto the temp branch, and resolve any merge conflicts
```
A---B---C---D---E---F  (master)
 \                  
  B'  (temp branch #1)
   \
    C`---D`---E`---F` (temp branch #2 - after resolving merge conflicts)
```

After that you can merge F` into master, or just copy the generated/modified files to the master branch.

It's not a perfect approach, and I'm still playing with it. Haven't yet "used it in production", but the initial tests look promising.

If you want to try it out, be careful not to mess up your git repository - the setup and the git commands can get a bit confusing, as there are a lot of files and branches involved.  I'll soon share an experimental tool I'm creating to help carry out the process for any adventurous folks out there.

**Comment by ronp001** [comment]
@Tapppi  - just to clarify my previous comment:  the outcome of the process is that all the changes you made to the code created by V1 of the generator are now applied as if you've made them to the code created by V2 of the generator.  If any of the changes can't be applied automatically, you're asked to fix them manually by solving the resulting merge conflict.

**Comment by ronp001** [comment]
@Tapppi @jondot - a preliminary version of the tool is up at https://github.com/ronp001/proj-maker

would love to hear your feedback if you're brave enough to check it out - and, as I noted in the README of the tool: be very careful when doing that.  my testing of the tool was limited to my own configuration, and I don't know how it will behave in other contexts. make sure your data is backed up before working with this.

**Comment by jondot** [comment]
Thanks @ronp001 for the new `hygen-create` tool. I'll be closing up this issue 👍

**Comment by Tapppi** [comment]
Great work guys, I'll give this a try as soon as I have a need for it, sorry but I'm quite swamped with other work atm ;)
