### ISSUE TITLE
Typescript support within hooks files 

### ISSUE THREAD

**Issue by Whoaa512** [jondot/hygen#163]
I'd like to be able to write my hooks files (`prompt.js` and `index.js`) in typescript.

Would you accept a patch that allows hooks files to be `.ts`?

Thinking to support this through the use of [ts-node](https://github.com/TypeStrong/ts-node)

**Comment by jondot** [comment]
Sounds good. I would accept such a thing, as long as it's optional since ts-node should slow down generation startup / runner considerably (we're aiming for 100ms startup).

**Comment by ConneXNL** [comment]
@Whoaa512 have you tried implementing such a feature?

**Comment by Whoaa512** [comment]
@ConneXNL I have not. My work has paused our investment into hygen for the moment.

I think you'd probably want to make changes here if you're planning to attempt this
https://github.com/jondot/hygen/blob/0d0b1b08dc6eed89a11ac90d2b74714887b8182e/src/prompt.ts#L11-L24

Maybe something like this?
```javascript
if (/\.ts$/.test(hooksFile)) {
  require('ts-node/register/transpile-only');
}
```
