### ISSUE TITLE
Unexpected type errors

### ISSUE THREAD

**Issue by noemission** [jondot/hygen#165]
Our generators started crashing with the error bellow
```
TypeError: Cannot create property 'inject' on number '0'
```
```
//generator.ejs.t
---
eof_last: 0
inject: true
to: "some.js"
append: true
---
hello world
```
It seems like the script tries to assign the property "inject" to the number "0" where it should do it to a proper object. The strange thing here is that the number 0 is right before the "inject" property on the front-matter. That made me search for an error in a "reduce" function or similar.

After a lot of search the problem seems to be in the line here:
https://github.com/jondot/hygen/blob/f9e0632f9c23fdac71e46697717a5f8f0c2c6b14/src/render.ts#L58

For some reason, you made the reduce to return the proper object only if the value is truthy. I am not sure if this has any purpose elsewhere (I am not familiar with the codebase) or if it's a mistake.
I think it's very common to have falsy values in the front-matter, like `null`, `0`, etc...

Is this a code mistake or am I missing something here?

**Comment by chrishale** [comment]
I did a bit of digging through the git history, and I think this bug will have been introduced [here](https://github.com/jondot/hygen/commit/bcbc793c88a51df9dc5be8bdb23deb7b3ac198ed) when Lodash was removed.

Originally `mapValues` was used:
```
L.mapValues(attributes, renderTemplate(_, args, config))
```

I think the vanilla implementation of this should be:
```
Object.entries(attributes).reduce(
  (obj, [key, value]) => {
    return {
      ...obj,
      [key]: renderTemplate(value, args, config),
    }
  },
  {},
)
```

**Comment by jondot** [comment]
merged, thanks!
