### ISSUE TITLE
Running hygen from hygen

### ISSUE THREAD

**Issue by berrylands** [jondot/hygen#168]
A fabulous package!

Is it possible to run hygen generators from hygen generators? Eg:

```
---
sh: "hygen redux add-action --myVariable myValue"
---
```

When I invoke this I get :

> Cannot find module '/Users/me/myproject/redux

**Comment by anithri** [comment]
It worked for me.  You have no name in the example.  Is that intentional?  After that, I'd check to make sure you aren't depending on something in the environment of where you are running the CLII from, that you don't have for the shell command.

**Comment by berrylands** [comment]
> It worked for me. You have no name in the example. Is that intentional? After that, I'd check to make sure you aren't depending on something in the environment of where you are running the CLII from, that you don't have for the shell command.

Thanks. I tried adding a name, but got the same result. Are you able to share your "sh:" string that worked for you?

**Comment by anithri** [comment]
```
---
sh: hygen gen with-prompt 'woot'
---
```

**Comment by berrylands** [comment]
Thanks for the reply.

I double-checked and tried it in this form again, but no joy. (I also have hygen v5.0.1, installed globally).

**Comment by jondot** [comment]
wow I never predicted someone running hygen from hygen, what a cool idea! ❤️ 
one more thing to consider -- are you running node through any shims? for example I use `asdf` which shims every node binary. In that case -- just for the sake of testing try: `node_modules/.bin/hygen ...` which should bypass any shell shims.

**Comment by berrylands** [comment]
Thanks. :-)

I'm not (knowingly) using shims. I tried your suggestion, but it didn't work because I'm using a global install of hygen. Your idea did prompt me to try a local install though (which I was hoping to avoid), and THAT WORKS! I can live with a local install - it's just another thing to do after I run CRA and then copy the _templates folder across.

Thanks again.
