### ISSUE TITLE
`hygen xxxxx-generator new xxxx` always generate hello.js

### ISSUE THREAD

**Issue by YuunYang** [jondot/hygen#171]
![image](https://user-images.githubusercontent.com/15278220/68834794-92eb4a80-06f1-11ea-85b2-d05a18352bbd.png)

`hygen xxxxx-generator new xxxx` always generate hello.js

**Comment by jondot** [comment]
Can you also add some of the templates? also -- if you have this project on github I can take a look and fix it for you
