### ISSUE TITLE
HYGEN_TMPLS does not work as documented

### ISSUE THREAD

**Issue by ronp001** [jondot/hygen#18]
hygen does not use the value in `HYGEN_TMPLS` as expected.

For example:
```bash
$ cd /dev/project
$ HYGEN_TMPLS=/home/me/_templates hygen
```
should look for templates in `/home/me/_templates`.

Actual behavior:  hygen looks for templates in ` /dev/project/home/me/_templates`.

(perhaps change `path.join(cwd, process.env.HYGEN_TMPLS || '_templates'),` to `process.env.HYGEN_TMPLS`  in `template-resolver.js`?)

**Comment by jondot** [comment]
Thanks! new version is currently building 👍

**Comment by jondot** [comment]
Great stuff Ron!
Really awesome, and can save a ton of time!
If you'd like to be featured under the hygen toolset, let me know. Currently there's

* `hygen-add` - adds packages from the outside world

We could make this into something like `hygen-create` or something like this.

There will be a section for ecosystem, as I'm getting a ton of requests and ideas from people all around, so this might be great for it!

Also if you're in TLV, I'd be happy to meet and see how you're using hygen 😎

**Comment by ronp001** [comment]
Thanks Jon - I'm glad you like it.

`hygen-create` sounds like a perfect name - and it would be great to have it featured as part of the toolset.  I'll rename it accordingly.

👍 meeting.  I'm usually in the Herzliya area.  Will reach out privately so we can coordinate.
