### ISSUE TITLE
Generating several files into a folder

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [jondot/hygen#180]
Hi @jondot !

I'm using Hygen to generate a folder and always included all these files:

- routes.name.js
- routes.definition.js
- routes.redirect.js
- index.js

I only need to change the folder's name & I accomplish it like so:

```
---
to: <%= folderName %>/routes.name.js
---
```
That works, but I'm trying to add the other files like so:

```
---
to: <%= folderName %>/routes.name.js
to: <%= folderName %>/routes.definition.js
to: <%= folderName %>/routes.redirect.js
to: <%= folderName %>/index.js
---
```
But it doesn't work & I get this error:

```
Loaded templates: _templates
YAMLException: duplicated mapping key at line 2, column 1:
    to: <%= folderName %>/routes.def ... 
    ^
Hygen v5.0.1

Available actions:
automatedRoutes: new
generator: help, new, with-prompt
```
How can I accomplish what I'm looking for? Thanks in advance!

**EDIT:**
I also asked the question in Stackoverflow [here](https://stackoverflow.com/questions/58866155/how-to-generate-multiple-files-on-the-same-path-with-hygen).

**Comment by Manuel-Suarez-Abascal** [comment]
Nevermind, I figured it out!

**Comment by codedplanetuk** [comment]
How did you solve this?
