### ISSUE TITLE
Conditionally render a file

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [jondot/hygen#181]
Hi @jondot I have been using Hygen at my work to automate Vue-Route files in the last days.

I'm trying to conditionally render a file with Hygen. This is my current code:
```
---
to: <%= folderName.toLowerCase() %>/routes.redirect.js
unless_exists: true
---
```
I'm trying to run the command `hygen new automatedRoutes --folderName clients` and if I add a `--redirect` flag... automatically will create the `routes.redirect.js` file & if I don't provide the `--redirect ` the file won't be created. Check this example:

File will be created:

```
hygen new automatedRoutes --folderName clients --redirect
```

File won't be created:
```
hygen new automatedRoutes --folderName clients
```

I have tried the following:

```
---
to: <%= folderName.toLowerCase()/ redirect ? 'routes.redirect.js' : null %>
unless_exists: true
---
```
But it doesn't work...I also tried [this](https://github.com/jondot/hygen/issues/23). Can you help me out to accomplish this behavior?

I'm generating many files into `--folderName` flag folder, but I need the `route.redirect.js` file to be optional, is there another way to accomplish this that I'm not aware of? Thanks in advance!

**Comment by jondot** [comment]
You can always use `/dev/null` as the file path if you don't want to generate, this will make hygen write to that path which of course means nothing gets created.

I'm debating with myself if to add a feature for conditional generating, it should be easy to add, its just that I'm unsure yet that it's a big pain.

For example, to implement conditional generation this way, I just keep multiple generators separately. In your case one with redirect and one without.

Again, happy to hear some more pain points around this, and if needed -- I'll implement as a built-in feature.

**Comment by Manuel-Suarez-Abascal** [comment]
> For example, to implement conditional generation this way, I just keep multiple generators separately. In your case one with redirect and one without.

Thanks for your fast reply. I might used this solution since I'm generating other files with the `automatedRoutes` generator:

```
/routes.name.js (required)
/routes.index.js (required)
/routes.definition.js (required)
/routes.redirect.js (optional)
```
Personally, I think everyone will benefit from having the option to conditionally generated files, like that we won't need to created two generators for accomplish this :)

**Comment by jondot** [comment]
Understood, no worries, it's pretty easy to implement. If you'd like to implement it and submit a PR, I can help you merge it.
Otherwise I'll mark this thread as an enhancement, and on the first chance I'll give it some time.

**Comment by Manuel-Suarez-Abascal** [comment]
@jondot finally I have found a workaround to solve my optional file rendering. My implementation uses the **`prompt`** with the **`type: 'confirm',`** like so:

**prompt.js file:**
```
module.exports = [
  {
    type: 'input',
    name: 'folder',
    message: 'Enter folder name?',
  },
  {
    type: 'input',
    name: 'module',
    message: 'Enter module name?',
  },
  {
    type: 'input',
    name: 'section',
    message: 'Enter section name?',
  },
  {
    type: 'confirm',
    name: 'redirect',
    message: 'Do you want to add a redirect route?',
  },
];
```

**routes.redirect.js (optional) file:**

```
---
to: "<%= redirect ? `/router/routes/${folder.toLowerCase().replace(/ +/g, '')}/routes.redirect.js` : null %>"
unless_exists: true
---
// Content to render goes here
```
**routes.definition.js file:**
```
---
to: /router/routes/<%= folder.toLowerCase().trim().replace(/\s+/g, '') %>/routes.definition.js
unless_exists: true
---
// Content to render goes here
```
**routes.name.js file:**
```
---
to: /router/routes/<%= folder.toLowerCase().trim().replace(/\s+/g, '') %>/routes.name.js
unless_exists: true
---
// Content to render goes here
```
**routes.index.js file:**
```
---
to: router/routes/<%= folder.toLowerCase().trim().replace(/\s+/g, '') %>/routes.index.js
unless_exists: true
---
// Content to render goes here
```
**Final Output:**
```
/router/routes/newRoutesFolderGoeshere/routes.name.js
/router/routes/newRoutesFolderGoeshere/routes.index.js
/router/routes/newRoutesFolderGoeshere/routes.definition.js
/router/routes/newRoutesFolderGoeshere/routes.redirect.js (optional)
```
Hopefully, it'll help somebody.

**Comment by Garwin4j** [comment]
Similar to the above, this worked for me: 
```
---
to: <% if(locals.storybook) { -%> src/components/<%= h.inflection.undasherize(name) %>/<%= h.inflection.undasherize(name) %>.story.tsx <% } else { %> null <% } -%>
---
```
