### ISSUE TITLE
Conditional Rendering crashes when `to:` is not the last attribute

### ISSUE THREAD

**Issue by grantbowering** [jondot/hygen#183]
It took me a painful while to figure out what was causing this, but it turns out that if you are using the [Conditional Rendering](http://www.hygen.io/templates#conditional-rendering) syntax, and there are any other attributes specified after the `to:`, the generator will explode if the condition is not met, saying that whichever attribute immediately follows the `to:` can't be added to an empty string:
```
TypeError: Cannot create property 'prepend' on string ''
details -----------
TypeError: Cannot create property 'prepend' on string ''
    at attributes.Object.entries.reduce ([...]\node_modules\hygen\lib\render.js:68:86)
    at Array.reduce (<anonymous>)
    at getFiles.then.then.then.then.then.then.then.map ([...]\node_modules\hygen\lib\render.js:68:46)
    at Array.map (<anonymous>)
    at arr ([...]\node_modules\hygen\lib\render.js:24:29)
    at <anonymous>
-------------------
```
I haven't done extensive testing, but just moving the `to:` attribute to be the last thing in the frontmatter block seems to make this error go away.
This problem was not yet present in 2.1.2, but was by 4.0.11, and still is in 5.0.3.  
If it can't easily be fixed, at least adding something to the documentation, and making sure that will come up in a google search for `"hygen" "cannot create property" "on string"`, would be a reasonable compromise.

**Comment by anithri** [comment]
Could you show us the code causing the error?

**Comment by grantbowering** [comment]
Sure.
A template originally had this frontmatter:
```
---
inject: true
to: "<%= rootModule ? 'src/modules/' + rootModule + '/reducer.ts' : null %>"
prepend: true
skip_if: reducer as <%= moduleNameCamel %>Reducer
---
```
After upgrading hygen from 2.1.2 to 4.0.11 or 5.0.3, this crashed as above.

Then I changed it to this, just moving where the `to:` is in the frontmatter block and changing nothing else,
```
---
inject: true
prepend: true
skip_if: reducer as <%= moduleNameCamel %>Reducer
to: "<%= rootModule ? 'src/modules/' + rootModule + '/reducer.ts' : null %>"
---
```

and then it works as expected.

**Comment by jondot** [comment]
In hygen v6.x this is no longer an issue (upcoming version), closing for now
