### ISSUE TITLE
Line ending on an injected line is missing the CR expected on Windows

### ISSUE THREAD

**Issue by grantbowering** [jondot/hygen#184]
After running a generator with a bunch of `inject` templates, I get errors from `prettier` in every spot that it injected.
![image](https://user-images.githubusercontent.com/2152220/69298298-a6ebec00-0bca-11ea-9c16-ec348e5e3cf7.png)
![image](https://user-images.githubusercontent.com/2152220/69298310-ae12fa00-0bca-11ea-9baa-47b4eded48ce.png)
Etc.

We're using `core.autocrlf` on our git repo, so it checks out `\r\n` on windows machines and commits `\n`.  So everything that gets pushed ends up with the same line endings in the repo, and everything that gets pulled should be homogenous in the local working directory also.
`prettier`'s `end-of-line` setting defaults to `"auto"`, which means it wants all of the line endings in the file to be whatever the first line ending in the file is. 
This causes no problem for anyone for two reasons: one, because of the autocrlf behavior of git, and two, because we mandated that everyone's editor automatically apply `eslint` and `prettier` on save.  So anything that has been round-tripped through the repo doesn't have mixed endings, and anything anyone has actually saved with VS Code doesn't have this problem either.
However, when you've just generated a bunch of files, and you keep getting `react-scripts` compile errors like above and have to open up each file just to Ctrl+S it without making any changes and then let it try to compile and find the next file you have to do that to, it's sorta frustrating.
It would be great if hygen's injector used the same behavior as prettier's end-of-line setting, grabbing the first line ending in the file and using that.
Or if it's lower-hanging fruit, this could also be taken care of by adding a configuration setting in a `.hygen.js` file that dictates what line ending to use.

**Comment by anithri** [comment]
I'm a bit confused, but I think you're saying that
1. In the repo line endings are stored `\n`
2. On windows, checking out code as `\r\n`
3. Hygen is using wrong line ending.

It's not clear which type of system you're running hygen on.  
Hygen uses `fs.win32` on windows machines and `fs.posix` everywhere else, but I don't think it does anything special for line endings, and uses the same style that the template uses.

I don't have a windows machine to test with though, so I could be wrong.

**Comment by grantbowering** [comment]
@anithri Sorry, my initial bug may not have been clear about two things:
 - I'm running on Windows (so my repo checks out with `\r\n`)
 - This only occurs on files that have had code injected into them
 - I titled this bug quite poorly, because it doesn't corrupt existing line endings; the only line endings that are unexpectedly missing `\r` are the ones on the end of an injected line. (I'd have to write a test to see if lines within the injection are correct, as all the injections I was working with last week were single-line.)
I'm not totally certain because I haven't had a chance to dig into it yet, but my current thoughts are that the issue is somewhere in the details of [injector.ts](https://github.com/jondot/hygen/blob/master/src/ops/injector.ts), dealing almost exclusively in `\n`'s.

**Comment by jondot** [comment]
thanks, should be fixed in next version
