### ISSUE TITLE
Is there anyway to include a template?

### ISSUE THREAD

**Issue by YuunYang** [jondot/hygen#185]
Thanks for your great project, but I got a problem
Like using ejs, we use `<%- include('Component/Field') %>` to include a `Filed` Component
![image](https://user-images.githubusercontent.com/15278220/69319230-c2620000-0c79-11ea-83ae-818f83fdc337.png)
![image](https://user-images.githubusercontent.com/15278220/69319255-c9890e00-0c79-11ea-948a-39448346129a.png)
![image](https://user-images.githubusercontent.com/15278220/69319511-40bea200-0c7a-11ea-9ea8-9a863e0f030a.png)
But, it seems doesn't work for me here, I checked my ejs code, but looks no problem.

**Comment by anithri** [comment]
I don't think you can nest ejs tags within other ejs.  Try something like...
```javascript
<%- include(`Component/${_c}` %>
```

**Comment by YuunYang** [comment]
> I don't think you can nest ejs tags within other ejs. Try something like...
> 
> ```js
> <%- include(`Component/${_c}` %>
> ```

![image](https://user-images.githubusercontent.com/15278220/69509792-3ef42780-0f75-11ea-8b96-d47f62cd7e98.png)
got this error, and if I set it to a constant text, it got the same error.
![image](https://user-images.githubusercontent.com/15278220/69509836-62b76d80-0f75-11ea-8c31-c8b14e5a1556.png)
Actually, if I changed the `Field` file, to make it raise a error, and it indeed caught this error. So I think the template was loaded, but by some reason, it returns a not found error

**Comment by YuunYang** [comment]
The solution is `include(`${actionfolder}/Component/${_c}`);`

**Comment by hrdwdmrbl** [comment]
For searchability / discovereability, I was trying to find this by searching for partials and nested. 

(I would love for this functionality to be documented to be documented!)
