### ISSUE TITLE
I can't generate the files in current working directory

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [jondot/hygen#189]
HI @jondot !

Currently, I'm trying to generate files in the current working directory. Following the docs, I have tried this:

```
---
to: <%= cwd %>/<%= module.toLowerCase().replace(/\s+/g, '-') %>/routes.definition.js
unless_exists: true
---
```
However, **`<%= cwd %>`**, it doesn't find dynamically the current directory that I'm sitting, but instead my project's root folder. 

Let's say my project is in **`/webapp/`**, but I want to navigate to **`/webapp/clients/<cwdFromWhereIRunTheScript>/<moduleDynamic>/<filesGoHere>`** why I can't accomplish it with `<%= cwd %>`. 

Thanks in advance!

**EDIT Update:**

I have been trying to use **`__dirname`**  like so:

```
to: <%= `${__dirname}` %>/<%= module.toLowerCase().replace(/\s+/g, '-') %>/routes.name.js
unless_exists: true
```
But it throws an error: **`__dirname is not defined`**

I still looking for way to solve this.

**EDIT UPDATE 2:**

:1st_place_medal: :tada: I have a created the first Hygen tag on stackoverflow. [Link here](https://stackoverflow.com/questions/59202536/hygen-dynamically-finding-the-current-working-directory-that-im-when-running-t)

**Comment by vospascal** [comment]
Bit late but for others 
try process.env.INIT_CWD
https://stackoverflow.com/questions/12238477/determine-command-line-working-directory-when-running-node-bin-script
