### ISSUE TITLE
Subaction should filter on filename, not on absolute path

### ISSUE THREAD

**Issue by thierrymichel** [jondot/hygen#192]
Hi,

First of all, thanks for the good job! 👍 

When using `$ hygen GENERATOR ACTION:SUBACTION`, it looks like subaction filtering is done on the  absolute path, not on the filename. I guess it's a bug…

- __Folder structure__ : `~/test/_template/foo/new/foo-bar.ejs.t`
- __Command__: `hygen foo new:test`

---

- __Results__: will match __test__ -> `/Users/me/test/_template/foo/new/foo-bar.ejs.t`
- __Expected__: no match

If I am not wrong, I can submit a PR…
Thanks

**Comment by jondot** [comment]
you're right. fixed!
