### ISSUE TITLE
Suggestion: support a way to separate rendering different template.

### ISSUE THREAD

**Issue by YuunYang** [jondot/hygen#196]
Like I need to render `form.ejs.t` and `index.ejs.t`, and I need using different data to render different template. so I want to support a way to step-by-step render different template, so I can handle different template.

**Comment by hpierre74** [comment]
There are several ways you could achieve that.
```bash
# generate all files, with a 'name' variable
$ hygen example-prompt new reporter


# generate one specific file, picked up based on the substring 'mailer'
$ hygen example-prompt new:mailer reporter


# generate all resources that correspond to a regular expression
$ hygen example-prompt 'new:.*html' reporter
```
Alternatively you could separate your files in different folders and use a script to play them one by one, compose prompts, etc...

Worth to mention, you can import anything you want inside `.hygen.js` (see the [extensibility docs](http://www.hygen.io/extensibility#hygenjs)) if you absolutely need to use the same file, in the same generator etc... you could implement some mapping function for your data that you'd attach to the helper module.

Finally, you could take advantage of the `ejs` syntax and write inline js using this syntax `<% ... -%>` which will not inject a line as opposed to `<%= ... %>` and make use of ternary inside the yaml top file declaration to do conditional rendering

**Comment by jondot** [comment]
thanks @hpierre74 looks like a great answer!
