### ISSUE TITLE
Suggestion: Referring to filename only (not path) in template

### ISSUE THREAD

**Issue by jonathanconway** [jondot/hygen#198]
Suppose I run the command:

```
hygen react-generator new src/components/loading-spinner
```

I want my template to be able to refer to just the "loading-spinner" part, rather than the whole "src/components/loading-spinner" path.

Currently this doesn't seem to be explicitly supported by hygen.

For now I'm using code like this:

```
<%= name.split('/').slice(-1)[0] %>
```

Could we implement this more explicitly in hygen, as either:

1. a built-in variable (the same way `name` is) or
2. a built-in helper?

BTW, many thanks to the founders and contributors for this project. It's very nice, clean and simple. Nice work!

**Comment by jondot** [comment]
thanks @jonathanconway 
I think this is a good contender for a `h.filename` helper to be added

**Comment by jondot** [comment]
actual implementation is now `h.path.basename(..)`, and `path` is your actual Node path module.
