### ISSUE TITLE
How can I force filename to be lowercase? 

### ISSUE THREAD

**Issue by banyan** [jondot/hygen#2]
Hi! Thanks for creating this tool! I have one question. 

Given this template: 
```
---
to: src/reducers/<%= name %>.ts
---
hi
```

`hygen redux new --name foo` will generate `src/reducers/foo.ts` and `hygen redux new --name Foo` will generate `src/reducers/Foo.ts`. I want to force filename to be lowercase even the user gives `Foo`. Can we do for that?

**Comment by jondot** [comment]
Hi,
Sure! just do this:

```
---
to: src/reducers/<%= name.toLowerCase() %>.ts
---
hi
```

**Comment by banyan** [comment]
ah okay thank you!

**Comment by jondot** [comment]
You're welcome!
