### ISSUE TITLE
Suggestion: Add all headings to Sidebar TOC

### ISSUE THREAD

**Issue by jsjoeio** [jondot/hygen#201]
Hi! 

I was going to open a PR but I think this would require a decent amount of work so I thought I'd propose it. 

While using `hygen`, one of the things I always have to look up is the "Helpers and Inflections" section but I always forget where it is. I'd love to help improve the docs so that it's easier to find. My first thought is, what if you added all the headings to the sidebar table of contents?

Thoughts?

**Comment by jondot** [comment]
It sounds like a great idea actually!

**Comment by jsjoeio** [comment]
Thanks for the quick reply! I'm glad to hear you think so 😄 I'll see if I can take a stab at this sometime this month. Luckily I have experience with Gatsby so I'm hoping I can figure it out relatively easily.

**Comment by jsjoeio** [comment]
If I'm being honest, I don't know if the effort is worth it for the gain in having that section in the TOC. 

I'll post my notes here though in case anyone else comes along and wants to chip in.

### How is the current Sidebar TOC generated?

Currently, there is a component called `toc.jsx`. This is a class component called `TableOfContents` with a few methods. `buildNodes` reads the array of `posts` from props. These `posts` are all the Markdown files you see in `content/docs`.

What this means then is we are building directly off of the posts themselves.

### What is the desired result?

It would be nice to add the headings and subheadings to the Sidebar TOC.

### Potential solution?

We need to somehow read the Markdown files, get the headings, generate links to them (skip links or page jumps) using the post slug, and then pass that information to the `TableOfContents` component. 

The question is: how can we read the Markdown files and when/where should that happen?

**Comment by jondot** [comment]
interesting, to read / parse markdown files I had great experience with the `mdast` toolchain, for example https://github.com/syntax-tree/mdast-util-toc. mdast and unist have an entire ecosystem that can satisfy many needs for parsing / manipulating markdown.

regarding where to plug the data in the node generation process, I guess someone in the gatsby lifecycle? but not sure.

an over-arching question would be, would moving to docusaurus help? I've had great experience with docusaurus 2.x, and if it helps, might be a good idea to move to it, which should be an easy task

**Comment by jondot** [comment]
I think anything that helps is great, no worries at all :)

Regarding docusaurus -- note that the 2.x version is close to Gatsby in spirit and so might save you time. From my experience docusaurus 2.x being alpha/beta doesn't really matter -- it's pretty stable and a few companies already "bet" on it.

Docs should be almost swap-in, the index/frontpage part, should be a little more involved, but i'm here for questions!

**Comment by jsjoeio** [comment]
Thanks for pointing that out about 2.x. I was looking at the stable version. 

I'll give this a go. Docusaurus has been something I've been wanting to play with. This is the perfect excuse.

> Docs should be almost swap-in, the index/frontpage part, should be a little more involved, but i'm here for questions!

Sounds good! Thanks Dotan :)
