### ISSUE TITLE
Scape for #

### ISSUE THREAD

**Issue by joelerll** [jondot/hygen#204]
I want generate a file for my .c project, but #include is recognized as a comment in the template

---
to: app/src/main.c
---

#include <stdio.h>

int main() {
    printf("Hello world");
    return 1;
}

**Comment by jc-anguiano** [comment]
how do you insert the code? did you tried using <%-variable%> instead <%=variable%> ?

**Comment by jondot** [comment]
we use EJS under the hood, please see here: https://ejs.co/
