### ISSUE TITLE
Is there a way to tag files so that Hygen is not allowed to change a part of a file?

### ISSUE THREAD

**Issue by haarse** [jondot/hygen#206]
Let me explain.
Let's say that we code generate a Standard file, let's pretend a file with all the attributes in an entity.
Then someone makes a customization in that file adding an attribute.
The next time we code generate we don't want to overwrite that customization.
Then we would like to tag the customization to avoid overwriting it.
Is this possible within Hygen?

Great tool anyway!

regards
Håkan

**Comment by sashaaKr** [comment]
@haarse did you check [`unless_exists: true`](http://www.hygen.io/templates#addition) option?

**Comment by jondot** [comment]
Tidying up and closing, feel free to reopen if still relevant
