### ISSUE TITLE
Global Utilities

### ISSUE THREAD

**Issue by kadoshms** [jondot/hygen#21]
Hey there!

First of all, great work, thanks.
I have a question though - is it possible to create a global utilities file and use it inside my templates?
Let's say I want to have a function that converts the following name `myComponent` to a dashed format `my-component`. 

I saw the built in utils, but what about custom ones?

Currently I have to copy paste this utility function to each of my templates, but it is obviously not a good way.

Is there an option to do so?

**Comment by jondot** [comment]
Hi Mor, you're welcome.

The general idea for hygen is that the utility you're looking for should already be there (take a look at what inflect offers (`inflection.dasherize( str )`).

In this specific case what you're looking for is already there, but in other cases where it's not, we'll be happy to include it in the core hygen codebase (as long as it's generic enough as a utility).

So, bottom line:

```
<%= h.inflection.dasherize('FooBar') %>
```
Should result in 'foo-bar'

**Comment by kadoshms** [comment]
Thanks for the quick reply, but I honestly think that letting developers add their own utilities is a really great feature that will empower this library :)

**Comment by jondot** [comment]
It’s a good idea. Plus in the current architecture it should be super easy to do.

What’s your take on how the API should look like?

**Comment by kadoshms** [comment]
Including files would be the best, but I am not sure how easy it would be to implement.
Another idea is to have a file that allows export to other files.

**Comment by alarie** [comment]
I'm kind of faking something like this right now making use of prompts. I use the `.when` callback of a "Are these settings correct?" prompt. This `.when` gets handed the complete `answers` object, so all your inquirer settings. And the best is, that's not a clone, but the reference to the same object that goes to the ejs renderer. So you can add your own props to that object which will then be passed to your templates. 

So while i'm not sure that functions defined on the `answers` would be passed to the ejs renderer, you could simply create shortcuts to all your camelCase, dash-case, PascalCase... props in the answers object and then simply use those properties without even having to call functions in the template:


```js
// prompt.js
import whatever from "whereever"

module.exports = [{
    type: 'confirm',
    name: 'ok',
    message: (answers) => `Are these settings correct?`,
    default: true,
    when: async (answers) => {
       answers.newPropCC = "newProp"
       answers.newPropPC = "NewProp"
       answers.newPropDC = "new-prop"
       ...

       return true // that's important, otherwise the message is never shown
    }
}]
```


```ejs
# template.ejs.t
---
to: path/to/file/<%= newPropCC %>.ts
---
```

In my case I use that callback mainly to run some shell scripts that generate more input for my later generators. (Getting data form SQL schemas to use in my templates later to be precise.)

It feels a little bit hacky and I would love to see this as a real feature somehow (esp. as the `answers` obj does not hold the `name` prop you pass via the `--name` flag).

**Comment by jondot** [comment]
@alarie awesome hack!
To sum up this issue, I know someone works on a mechanism to load global helpers. I'll close this for now but in exchange I'll open up a 'Roadmap' issue to track progress.

**Comment by jondot** [comment]
Update: hygen now supports global helpers, see more here: http://www.hygen.io/extensibility
