### ISSUE TITLE
Add a way to access the frontmatter values

### ISSUE THREAD

**Issue by KnisterPeter** [jondot/hygen#214]
Hi,

I would like to see access to the frontmatter values in the template. My use case for this are relative paths I need to compute. To be more concrete:

I have a template which is written into a dynamic path based on the variables given. Then I want to write something in the template which addresses another file in my repository (a `tsconfig.json` which should be extended). To do that I need to know how many steps (e.g. '..') I have to add to reach that file.
I can add a helper to do that, but since the helper has no access to the frontmatter values, and also the template does not have access to them I have to duplicate the `to: ` value.
It would be really nice to have the frontmatter values as predefined variables like `actionfolder` and the others.

**Comment by jondot** [comment]
Thanks for the idea, should be in the next version
