### ISSUE TITLE
Name variable should be PascalCase

### ISSUE THREAD

**Issue by danielo515** [jondot/hygen#219]
Hello, I noticed that, when you pass an already camel case name, the variable `Name`  loses its casing.
So for example:

```
create component newComponent
```

Will create `Newcomponent` instead of `NewComponent` as expected.
It will be as easy as just uppercasing the first letter instead of formatting the entire word. Or maybe just use PascalCase instead of whatever you are using right now.

Regards

**Comment by jondot** [comment]
Thanks, should be good now
