### ISSUE TITLE
Conditionally use templates?

### ISSUE THREAD

**Issue by chrisdothtml** [jondot/hygen#22]
For example, if I wanted support a `--withCSS` flag:

---

`hygen component new --name foo`

**components/foo.js**

```javascript
export default function foo () {}
```

---

`hygen component new --name foo --withCSS`

**components/name/foo.js**

```javascript
import './foo.css'

export default function foo () {}
```

**components/name/foo.css**

```css
.foo {
  /**/
}
```

---

As far as I can tell there's no way to conditionally determine whether to add that `foo.css` file

**Comment by jondot** [comment]
Did you take a look at subcommands? They allow to run a subset of a generator action

**Comment by jondot** [comment]
Hi!
I think this issue is similar to the current one: https://github.com/jondot/hygen/issues/23
I believe the solution is relevant to your case as well so I'll close this one. Please feel free to reopen if needed
