### ISSUE TITLE
message displayed after sh

### ISSUE THREAD

**Issue by fyyyyy** [jondot/hygen#221]
I have a script template which adds dev dependencies to package.json and installs those dependencies. However it seems that message is always rendered at the very end of the generator process. I would like to somehow inform the user during the long installation process on what is happening. Therefore logging the message before sh execution would be convenient.

related: #50 

```
---
inject: true
to: package.json
message: installing dev dependencies...
after: devDependencies
skip_if: storybook/addon-docs
sh: cd <%= cwd %> && npm i
---
    "@storybook/addon-docs": "latest",
    "@storybook/addon-knobs": "latest",
    "@storybook/addon-notes": "latest",
    "@storybook/addon-storysource": "latest",
    "@storybook/html": "latest",
```

**Comment by jondot** [comment]
Interesting. I'm checking this...

**Comment by jondot** [comment]
Regarding combination of this issue and 
https://github.com/jondot/hygen/issues/50

How about using Hygen's config capabilties?
For example if you place your own 'exec' in `.hygen.js` it will pick it up instead

**Comment by fyyyyy** [comment]
I've done so, but message is generally logged when the sh command succeeds. Which is fine, i guess when you see it as a success message.

Maybe hygen could then also add:
```
error: "This only shows when sh: or template fails"
info: "This always shows before executing sh or template"
```

**Comment by jondot** [comment]
that's interesting. I think it can easily be added, plus -- right now exec ignores the binary exit conditions completely; so your solution fits well.
Just to namespace the attribute names, how about:

```
sh_pre: ..
sh_post: ..
sh_err: ...
```

**Comment by LassiterJ** [comment]
Also looking for a good solution for logging to console!

**Comment by jondot** [comment]
handled via #316
