### ISSUE TITLE
Naming a template file `index` breaks generator

### ISSUE THREAD

**Issue by seaneking** [jondot/hygen#222]
Just stumbled across what seems to be an undocumented gotcha — Hygen doesn't pick up on template files that are named `index.{ext}`. For example I had a React component template with `index.ejs` and `component.stories.ejs`, the latter worked fine but the former wasn't being read. Changed it to `compnoent.ejs` and it worked fine.

Not a problem but worth documenting if it is a known limitation.

**Comment by fyyyyy** [comment]
index.js is for the hygen prompt. If you want an index file, put in in a folder and it will work fine or rename to _index.{ext}

**Comment by jondot** [comment]
Yup. sorry for that, but in order to have less friction hygen adopts convention over configuration. In that case a file named 'index.js' cannot be used as a template name, and I'd go for what @fyyyyy is suggesting.
Thanks!

**Comment by seaneking** [comment]
Yep sounds good, might be worth documenting though if it’s not already (I didn’t see any docs mentioning this?)
