### ISSUE TITLE
End with proper exit codes on error

### ISSUE THREAD

**Issue by manuel-mauky** [jondot/hygen#225]
Hygen ends with exit code 0 even if there was an error (for example an invalid action was passed as argument). 
This makes it hard to use the tool in scripts because you can't detect errors.

Looking at the code I've found [this line in index.ts](https://github.com/jondot/hygen/blob/master/src/index.ts#L26) which looks suspicious because the `process.exit(1)` is commented out. However, I'm not sure if I understand the flow in the code correctly.

**Comment by jondot** [comment]
you are correct. I believe this has to do with embedding hygen (which is the best way to use it for programmable cases). either way I will fix this and it'll be ready for v6.x to be released later today
thanks!
