### ISSUE TITLE
from: and to:

### ISSUE THREAD

**Issue by fyyyyy** [jondot/hygen#226]
Having a `from: ` method in the templates would be useful for creating shared templates.
The `from:` method would read the template and overwrite additional methods if provided, e.g. we can overwrite `to:` in our generator.

So, we could create a folder for e.g. __templates/common/..._ and use those shared templates in our generators by overwriting `to:`

E.g.

```
---
from: ../common/configs/eslint.rc
to: /packages/<%= name %>/eslint.rc
---
```

**Comment by jondot** [comment]
merged!
