### ISSUE TITLE
Installing the latest version of hygen (5.0.3) leads to `yarn audit` vulnerabilities (yargs-parser)

### ISSUE THREAD

**Issue by invalidred** [jondot/hygen#227]
```
yarn audit
```

<img width="695" alt="Screen Shot 2020-05-27 at 9 25 55 AM" src="https://user-images.githubusercontent.com/5270458/83024248-191b0e80-9ffc-11ea-82dc-2e9f17a9e3ac.png">

**Comment by jondot** [comment]
I've just updated all deps resulting in perf boost and security patches.
Will release v6.x later on, thanks!
