### ISSUE TITLE
If true, generate file

### ISSUE THREAD

**Issue by sebastienrocks** [jondot/hygen#23]
Hi,

I'm playing around with Hygen, creating templates for repeated tasks I have. However I am looking for a solution to my issue:

I have a conditional logic in my generator prompt which is a boolean. I would like to generate a file or not depending on this value.

Is this at all possible? I've seen `skip_if` however this seems to work only for inject and is regex based.

Any ideas / solutions would be great. Thanks

**Comment by jondot** [comment]
Hi,
This should work:

```
---
to: "<%= message ? 'app/hello.js' : null %>"
---
etc.
```

Did you try that yet?

**Comment by sebastienrocks** [comment]
Yes I must have overlooked this. This fits what I need, thanks for that.

**Comment by jondot** [comment]
Great! I've added documentation about this, but frankly without your issue many more people might have overlooked it 😎 . Thanks for your contribution!

http://www.hygen.io/templates/#conditional-rendering

**Comment by aniruddha-mithya** [comment]
> Great! I've just added documentation about this, so frankly without your issue many more people might have overlooked it 😎 . Thanks for your contribution!
> 
> http://www.hygen.io/templates/#conditional-rendering

This link leads to a 404. Could you please update the link? Haven't been able to find it.

**Comment by StasNemy** [comment]
You can specify the path to a non-existent file like this

```
to: <% if ([variable from prompt]) { %>null<% } else { %>[normalPath]<% } %>
```

**UPD:**
```
skip_if: <%= isSkip %> 
```

**Comment by aniruddha-mithya** [comment]
The correct url is: http://www.hygen.io/docs/templates#conditional-rendering
