### ISSUE TITLE
Should prompt values override argument values

### ISSUE THREAD

**Issue by jgornick** [jondot/hygen#231]
I've run into a use case where I want to use prompts to make sure required arguments have been provided, and if they are, format and validate using the prompts correctly.

For example, I can setup my prompt.js as:

```typescript
  // ...
  prompt: async ({ prompter, args }) => {
    return {
      ...await prompter.prompt({
        name: 'scriptName',
        type: 'input',
        message: 'What script should we add it to?',
        skip: () => args.scriptName !== undefined,
        initial: args.scriptName,
        format: kebabCase,
        result: kebabCase,
      }),
      ...await prompter.prompt({
        name: 'commandName',
        type: 'input',
        message: 'What command name should we use?',
        skip: () => args.commandName !== undefined,
        initial: args.commandName,
        format: kebabCase,
        result: kebabCase,
      }),
    }
  },
  // ...
```

In this case, I want to prompt the user to provide in addition to `name`, a `scriptName` and `commandName`. However, I don't want to prompt the user for the input if they've already provided through the arguments. For example:

`hygen foo create-bar barName --script-name fooBar`

... would only prompt for `commandName`, but `scriptName` would *not* be prompted. Also, since the `scriptName` argument was provided, the prompt will still run the `result` handler, kebab'ing the `fooBar` to `foo-bar`.

Now I would expect in my templates to use `<%= scriptName %>` and `<%= commandName %>` directly.

Based on a little digging, we found that this might be a really easy fix. Looking at [hygen/params.ts at 1ccc4912f45f1ef18f6c4dc21f554d27e80e29f0 · jondot/hygen](https://github.com/jondot/hygen/blob/1ccc4912f45f1ef18f6c4dc21f554d27e80e29f0/src/params.ts#L36-L37), if the `cleanArgv` and `promptArgs` lines are swapped in the `Object.assign`, then the prompts could override/extend the argument values.

Thoughts?

**Comment by jgornick** [comment]
Now thinking about this a bit more too, the `name` argument could also be prompted if the user doesn't provide one. This could be a better experience when a user forgets to include a name and is not left with `unnamed` as the default name.

**Comment by fyyyyy** [comment]
Especially when you build validations on the name prompt. The user could supply an incorrect name and with the current implementation the result from prompt would be simply ignored.
Imo promptArgs should come last.

   ```
 const args = Object.assign({
        templates,
        actionfolder,
        generator,
        action,
        subaction,
    }, cleanArgv, name && { name }, promptArgs);
```

**Comment by jondot** [comment]
Looks like a good idea, will implement this per @fyyyyy latest version

**Comment by jondot** [comment]
Should be good now, closing up, thanks for the idea!
