### ISSUE TITLE
[BUG] Add a new Filter in rendering process for files with conditional rendering

### ISSUE THREAD

**Issue by Saeid-Za** [jondot/hygen#232]
When using conditional rendering, if a template is resolved to have `null` value for `to` key, no more variable resolving should be followed. current implementation, try to resolve all the template variables before starting the rendering process. this behavior is problematic when the existence of a variable is dependent on the value of an other.

consider this config:

```

const questions = [
  {
    type: "input",
    name: "componentName",
    message: "Name of the Component? 🔥",
    validate: (val)=>!!val,
  },
  {
    type: "confirm",
    name: "hasList",
    message: "Need List Page Too? ❓",
    initial: true,
  }
]

const listQuestions = [
  {
    type: "confirm",
    name: "hasPagination",
    message: "Need Pagination for List? ❓",
    initial: true,
  }
]

module.exports = {
  prompt: ({ prompter, args }) => {
    return  prompter
    .prompt(questions)
    .then((answers) =>{
      const {hasList} = answers;
      const nextQuestions = [];
      if(hasList)
        nextQuestions.push(...listQuestions)

      return prompter.prompt(nextQuestions)
      .then(nextAnswers => Object.assign({}, answers, nextAnswers))
    })
  } 
 
```

if variable `hasList` is used as rendering condition of template `A` and be prompted to `false`, `hasPagination` will never have any value, and an error will be thrown when trying to render `A`.
Error Message :
`hasPagination is not defined
`

**Comment by jondot** [comment]
Not sure I follow the use case (still trying to figure out where 'to' exists here) -- could you give a concrete example? maybe in a sample repo?

**Comment by Saeid-Za** [comment]
Sure!, sorry if the previous comment was vague.
consider the mentioned prompt file and the following template: 
```
---
to: "<%= hasList ? ('./' + componentListName + '.ts') : null %>"
---

@Component({})
export default class <%= componentListName %> extends Vue {

  tableConfig = {
    loading: false,
    data: [],
    pagination: {
      page: 1,
      rowsPerPage: 5,
      <%_ if (hasPagination) { -%>
      rowsNumber: 0,
      <%_ } -%>
    },
  }

}

```
here, the variable `hasList` is being used as a rendering condition for the template. if the the value of that variable is prompted to be `false`, the template would never render and would not use `hasPagination`.
I think the current rendering process, would try to render the whole template then throw it away.
in that process, the variable `hasPagination` is accessed while undefined and an error is thrown.
if rendering condition is resolved to be `null`, then renderer should skip rendering that template.
hope this comment clarifies the issue.

**Comment by jondot** [comment]
Oh! got it. That is an interesting use case. I can check it quickly.

**Comment by jondot** [comment]
I believe you are correct, I think in order to resolve this we will have to break the engine into a 2-pass rendering engine, first render attributes, filter, and then render all bodies. Off the bat I can gauge this to be a deep refactor, and I'm wondering if we can get a workaround and delay this rewrite, maybe default values for things like hasPagination will work?

**Comment by Saeid-Za** [comment]
I see. there is a workaround as you mentioned, in fact i'm already using it in my `prompt` file.
something like this would provide a default value that would be overwritten if a new value is provided.
```
module.exports = {
  prompt: ({ prompter, args }) => {
    return  prompter
    .prompt(questions)
    .then((answers) =>{
      const {hasList} = answers;
      const nextQuestions = [];
      if(hasList)
        nextQuestions.push(...listQuestions)

      return prompter.prompt(nextQuestions)
      .then(nextAnswers => Object.assign({hasPagination: false}, answers, nextAnswers))
    })
  } 
 
}
```

**Comment by jondot** [comment]
If that makes sense to you, I'm happy. Also willing to accept a PR if you have a quick idea to resolve :)
Will close this for now, feel free to reopen
