### ISSUE TITLE
recursive template listing and execution

### ISSUE THREAD

**Issue by jfols** [jondot/hygen#24]
This is just a nice to have ;)

It'd be great to have `hygen` at the top level of a project recursively search and list all actions spread throughout the project, current behavior only searches the current directory's `_templates` directory.

Here's a hasty hack I used in npm scripts:

`"templates": "find . -path ./node_modules -prune -o -type d | grep '_templates/[A-z_\\-]*/[A-z_\\-]*'",`

Then `npm run templates` yields:

```
> find . -path ./node_modules -prune -o -type d | grep '_templates/[A-z_\-]*/[A-z_\-]*'

./_templates/component/new-connected
./_templates/component/new
./_templates/generator/with-prompt
./_templates/generator/new
./_templates/generator/help
./_templates/icon/new
./imports/both/collections/_templates/new/collection
./imports/server/fixtures/_templates/new/fixture
./imports/server/cron/_templates/new/cron
./imports/client/atoms/_templates/new/atom
./imports/client/layouts/_templates/new/layout
./imports/client/redux/_templates/new/reducer
./imports/client/redux/_templates/new/action
./imports/client/routes/_templates/new/route
./imports/client/organisms/_templates/new/organism
```

The ability to execute `hygen new atom` from the top level of the project would be awesome.

**Comment by jondot** [comment]
That's awsome!
There's at least one person I know of who's working on such a thing to contribute. Let's see what he comes up with and align to your idea :cool:

**Comment by jondot** [comment]
Moved this to Roadmap, thanks!

**Comment by jfols** [comment]
I've come up with a pretty simple solution to this--just write `npm` scripts. It would be cool if `hygen` worked like this out of the box.

```
    "new.action": "cd imports/client/redux; hygen new action",
    "new.reducer": "cd imports/client/redux; hygen new reducer",
    "new.atom": "cd imports/client/____atoms; hygen new atom",
    "new.molecule": "cd imports/client/___molecules; hygen new molecule",
    "new.organism": "cd imports/client/__organisms; hygen new organism",
    "new.layout": "cd imports/client/_layouts; hygen new",
```

**Comment by jondot** [comment]
That's brilliant! 🥇
