### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by qm3ster** [jondot/hygen#25]
Quick Start ends with links to templates and generators.

If you are on /quick-start/ (note the trailing slash), these lead to /quick-start/templates, etc.

**Comment by jondot** [comment]
This is odd. Can you tell me what browser are you using?

**Comment by jondot** [comment]
In any case I've updated the site. Thanks for the catch!

**Comment by qm3ster** [comment]
Chromium 64.0.3282.167 running on Ubuntu 17.10
