### ISSUE TITLE
Create prompt template via template

### ISSUE THREAD

**Issue by chiefchief** [jondot/hygen#250]
Hello, i'm using hygen for generating project, and i want generate a project depending on the conditions
i'm creating templates for both condition
in in both conditions i need different files, one of the condition need prompt file other one - no
its easy to generate prompt file 

GENERATION PROMPT FILE
```
---
to: _templates/generate/helper/prompt.js
---
module.exports = [
  {
    type: 'input',
    name: 'name',
    message: 'Enter helper name...',
  },
];
```
but also i need files depends on this prompt, and i'm trying to do something like this
```
---
to: _templates/generate/helper/helperFile.ejs.t
---
---
to: src/helpers/<%=h.changeCase.camelCase(name)%>.ts
---
...some code
```

but i got
```
---
to: src/helpers/unnamed.ts
---
...some code
```

is it possible to do what i need?

**Comment by jondot** [comment]
not sure what you are trying to do, please create a minimal repo that shows the problem and reopen if relevant, thanks
