### ISSUE TITLE
What could be the problem with before tag not running correctly locally?

### ISSUE THREAD

**Issue by vkhobor** [jondot/hygen#252]
I was trying to inject before a line with the ` before: ` tag, but it instead injected in the first line of the file. 
If there was no match it did not inject but otherwise it worked like prepend or append.
```
---
to: file.test
inject: true
before: before_this
---
injection
```

```
injection
thing
after_this

before_this
thing
```

I checked in an online dev enviroment (gitpod)and there this wasn't an issue. So it is probably not a bug. 
What could be wrong with my local setup?
Thank you.

**Comment by seansellek** [comment]
@vkhobor what operating system are you on?

**Comment by vkhobor** [comment]
Windows 10.

**Comment by seansellek** [comment]
I believe you are seeing the issue I describe here: https://github.com/jondot/hygen/issues/255#issuecomment-674997358

**Comment by vkhobor** [comment]
Thank you very much.👌It is the same problem.
