### ISSUE TITLE
'Build your own' example does not work, chalk/templates module not found

### ISSUE THREAD

**Issue by csi-lk** [jondot/hygen#253]
Unless i'm missing something using the code from the README.md results in:

```
Error: Cannot find module 'chalk/templates'
```

Even with deps as:

```
  "dependencies": {
    "chalk": "4.1.0",
    "enquirer": "2.3.6",
    "execa": "4.0.3",
    "hygen": "6.0.4"
  },
```

I've also put together an example sandbox here: (see the terminal output on the RHS)

https://codesandbox.io/s/hygen-chalk-bug-2o4u6

---

Seems to be related to the logger loading `chalk/templates`

Looking at the `chalk` package it does have `templates.js` in it's `source` dir

Changing `hygen/lib/logger.js:10` to

```
const template = require('chalk/source/templates');
```

Seems to fix it, I can submit this as a PR but didn't know whether this would affect the common usecase of running the tool as a cli

thought it warranted a discussion

Cheers

**Comment by csi-lk** [comment]
Update

It looks like the `lib` folder is older code? but everything in `dist` is the newer typescript code?

Managed to figure out if you reference the `dist/logger` file it works fine

```
const Logger = require('hygen/dist/logger').default;
```

If this is correct it may be worth updating the README

I can submit a PR for this if you'd like

**Comment by MikeyBeLike** [comment]
@csi-lk hi!

had a PR here waiting that fixes this: https://github.com/jondot/hygen/pull/248
