### ISSUE TITLE
sh: echo in inject templates fails under linux/docker

### ISSUE THREAD

**Issue by fyyyyy** [jondot/hygen#259]
Using `sh: echo` throws an unknown error for `inject:true` templates under linux/docker
Docker Image used: 
`FROM node:12.18.3-alpine`

The inject command executes (its adding the scripts to pacakge.json) but then hygen exists without an error msg.
Removing sh: echo fixes the issue. 

```
---
eof_last: false
inject: true
to: <%= name %>/package.json
before: devDependencies
sh: echo "adding dev depencies"
skip_if: clean:build
---
  "scripts": {
    "bootstrap": "lerna bootstrap",
    "build": "lerna run build",
    ....
```

**Comment by jondot** [comment]
not sure how to repro, may be specific linux distro?
please open if this persist
