### ISSUE TITLE
Documentation - Link to /generators page is broken (page does not exist)

### ISSUE THREAD

**Issue by novellac** [jondot/hygen#264]
**Context**
When I did an internet search, one of the results pointed to http://www.hygen.io/generators/. I clicked on this link but it led to a 404. I was able to work around this by going to the Docs page and looking for Generators (which I found at http://www.hygen.io/docs/generators).

**Possible Solution**
If possible, include a redirect from `/generators/` to `/docs/generators`.

**Comment by ilyakamens** [comment]
The same issue occurs for the FAQ page linked to [here](https://github.com/jondot/hygen/issues/1).
