### ISSUE TITLE
Template option "force" ignored

### ISSUE THREAD

**Issue by Roms1383** [jondot/hygen#271]
Hello everybody, first and foremost thanks for this library it's refreshing !

#### Description
I ran into an issue where the parameter `force` in the template is being ignored.

#### Steps to reproduce :

Given this project tree :

<img width="260" alt="Screen Shot 2020-10-28 at 18 06 44" src="https://user-images.githubusercontent.com/21016014/97428383-7ec34c00-1948-11eb-9e11-4a36fa13bd00.png">

With this simplified setup :

__templates/dotfile/nvm/new.ejs.t_
```ejs
---
to: .nvmrc
force: true
---

<%= node_version %>
```

_package.json_
```js
{
  "name": "@roms1383/generators",
  "version": "0.0.1",
  "files": [
    "_templates/**",
    // ...
  ],
  // ...
  "scripts": {
    "test": "npx hygen dotfile nvm:new --node_version 12.19.0"
  }
}
```

> p.s : my local repo is `npm link`ed so I can run generators easily.

#### Expected result

The existing `.nvmrc` in the repo should be overriden without prompting the user.

#### Given result

<img width="551" alt="Screen Shot 2020-10-28 at 17 56 45" src="https://user-images.githubusercontent.com/21016014/97428643-dd88c580-1948-11eb-898e-44b7adffa67c.png">

TBH I haven't investigated further as this is a non-blocking issue for me at the moment, but I report in case.

**Edit** : I use `hygen` v6.0.4

**Comment by minsangk** [comment]
I had the same issue on this.
My PR on https://github.com/jondot/hygen/pull/272
