### ISSUE TITLE
Recursive template inclusion

### ISSUE THREAD

**Issue by tobmaster** [jondot/hygen#28]
It would be super useful for code organization to leverage subdirectories.
To enable structures like:
```
my_generator 
├ action
 ├ tests
   ├mytest.ejs
 ├ myclass.ejs
 ├ prompt.js
 ├ injections
  ├ myinject.ejs
```

Regarding the order I would suggest that the templates-resolver first collects all root level templates then all directory templates in the alphabetical order of the folder name.

Alternatively the template-resolver could be injected into the runner via the config to enable people to make their own template-resolve logic

**Comment by jondot** [comment]
Yup, that sounds like a great idea. The reason I've hesitated yet to do that - is that it makes much less code to just list out two-level directories.

The tradeoff was Hygen template resolving being more dumb = less code = less assumptions about what users want, and so less code and features that no one needs :)

If you have an elegant way of implementing this (also - mind the performance penalty of scanning multilevels), I'd be super happy to see a PR and review it with you!

**Comment by tobmaster** [comment]
I see. Ok, then I close that issue. Thx for explaining

**Comment by jondot** [comment]
Cool, don't get me wrong though, I would love to see this happening, just waiting for the right implementation so feel free to hack on it 😎

**Comment by tobmaster** [comment]
No worries. I might have a look at it anyways ;)
