### ISSUE TITLE
pass a variable down to a from

### ISSUE THREAD

**Issue by xenoterracide** [jondot/hygen#280]
this might be possible and is related to #279 

I want to be able to pass a variable down to a from template, as it is basically the same, changing just one static thing.

**Comment by airtonix** [comment]
in the mean time you could solve it like this instead: https://github.com/jondot/hygen/issues/286#issuecomment-755288782

**Comment by xenoterracide** [comment]
I just decided to go and write my own thing instead of using hygen. hygen seems nice but after hitting too many issues (specifically a big one when I tried to have the same templates in multiple ... factories? ) I just gave up on it.
