### ISSUE TITLE
Shared templates don't have access to generator variables

### ISSUE THREAD

**Issue by billsaysthis** [jondot/hygen#286]
For example I would like to have one generator optionally generate the files from a second generator but using the `to:/from` approach fails because the second generator templates are just printed as text. Even the frontmatter section is printed in the output files.

**Comment by ihadgraft** [comment]
Since this is using ejs, you can load any file in unescaped as part of the body and it will be processed. This opens up the possibility to assemble snippets to further compose larger files for various contexts.

```
---
to: <%= projectName %>/path/to/output-file.txt
---
<%- include(`${templates}/path/to/shared-template.text`) %>
```

**Comment by billsaysthis** [comment]
How does this give me access to generator variables in the included file??

**Comment by ihadgraft** [comment]
In my experience, the included file has access to all variables as the file it is being included from.

For example if you have the following `_templates/shared-file.txt`.

```
Hello, <%= name %>
```
And include it with:

```
---
to: output.txt
---
<%- include(`${templates}/shared-file.txt`) %>
```

Assuming you have set `name` by prompting or passing an arg (e.g. --name='John Doe'), it'll print "Hello, John Doe".

**Comment by cwilso03** [comment]
> In my experience, the included file has access to all variables as the file it is being included from.
Unfortunately, this workaround doesn't seem to work.  The shared file is included, but no ejs replacement is done at all.

**Comment by samcraigdev** [comment]
Using a hack similar to the following:

```js
module.exports = {
  // ...
  helpers: {
    // ...
    render: (path, data) => {
      let template;
      template = fs.readFileSync(path, "utf8");
      template = template.replace(/^---\n(.*)\n---/g, "");

      const output = ejs.render(template, data);
      return output;
    }
  },
};
```
And then, in a given template you can reference via:

```ejs
<%- h.render(`${templates}/foo/bar/foobar.ejs.t`, { ...locals, foo: "bar" }) %>
```

**Comment by jondot** [comment]
Need to use the EJS construct:
https://stackoverflow.com/questions/29196562/how-to-include-a-template-with-parameters-in-ejs

Please reopen if this persist for you
