### ISSUE TITLE
Injecting after or before not working on windows environments

### ISSUE THREAD

**Issue by michalklim** [jondot/hygen#288]
When using templates with injecting `after` or `before` are not respected on windows environment and instead content is injected at the beginning or end of the file respectively. It works on unix environment as expected

**Template:**
```ejs
---
to: foo/file.js
inject: true
after: HOOK
---
foobar
```

**Expected result** 
```js
// foo/file.js

function foo() {
   // HOOK
   foobar
}
```

**Actual result**
```js
// foo/file.js

function foo() {
   // HOOK
}
foobar
```

It works fine when I downgraded to version 5.0.3

**Comment by shahab65** [comment]
I have exactly the same problem.
It works great on ubuntu system. 
but it doesn't work on windows which my colleges use.

**Comment by Omhet** [comment]
The same for me. Doesn't work for Windows 10 with hygen@6.0.4. However, it works on 5.0.3 version

Btw, didn't test it with other OS
