### ISSUE TITLE
Generate multiple files from a config object

### ISSUE THREAD

**Issue by daltongray** [jondot/hygen#294]
I can't find this in the Hygen of ejs docs. Perhaps someone can point it out to me if I've missed something. 

I have an object literal that I want to generate multiple files from using hygen. 

`
const config = {
    docTypeOne : {
      Foo:{}
      Bar: {}
   }
    docTypeTwo : {
      Foo:{}
      Bar: {}
    }
}
`

I want to generate different docs based on the type, in multiple locations. The end result might look like: 

Directory...
 - docTypeOneCollection
      - foo.js
      - bar.js
 - docTypeTwoCollection
        - foo.js
        - bar.js

How would I go about doing that? 

Having trouble wrapping my head around how to create multiple front matters...

**Comment by valinagacevschi** [comment]
First you should build your 'foo.js` and `bar.js` templates and parametrize the destination:
```
---
to: <%= absPath %>/foo.js
---
```
Then you can have an `index.js` file to do the work:
```
module.exports = {
  prompt: ({ inquirer, args }) => {
    const questions = [
       ...
    ]
    return inquirer
      .prompt(questions)
      .then(answers => {
        // parse your config here and prepare the props then add them in returned object
        // const absPath = ...
        return { ...answers, absPath, docTypeOne, docTypeTwo }
      })
```

**Comment by jondot** [comment]
will be handled via #322
