### ISSUE TITLE
replacing line of file

### ISSUE THREAD

**Issue by shahab65** [jondot/hygen#295]
I have this line of code in my package.json file:
```json 
    "build": "react-scripts build",
```
I want to replace it with this line:
```json
  "build": "my command",
```
I have written this for making this happen:
```console
---
to: package.json
after: "start"
inject: true
---
  "build": "my command",

```
But what I get is this:
```json
    "build": "my command",
    "build": "react-scripts build",
```
How can I remove the old code?   
thanks

**Comment by valinagacevschi** [comment]
You cannot replace a line. however you can do something like this during inject:
```
<%if (some_condition) {-%>
    "build": "my command",
<%} else { -%>
    "build": "react-scripts build",
<% } -%>
```

**Comment by shahab65** [comment]
> You cannot replace a line. however you can do something like this during inject:
> 
> ```
> <%if (some_condition) {-%>
>     "build": "my command",
> <%} else { -%>
>     "build": "react-scripts build",
> <% } -%>
> ```

thank you for your response.
this doesn't help me because the build command is there already.  
I need to remove it and replace it with another line of code

**Comment by shahab65** [comment]
I ended up removing the old command with bash script
```bash
sed  -i  's/"build".*//' package.json
```
then I used my template for adding the new build command

**Comment by airtonix** [comment]
I'm probs a bit late on this, but instead of sed, you can also use : 

```
---
sh: npx npe scripts.build "my command"
---
```
https://www.npmjs.com/package/npe
