### ISSUE TITLE
Does hygen support plural? 

### ISSUE THREAD

**Issue by banyan** [jondot/hygen#3]
Can we transform a word to be a plural? Or any other way using a library?

**Comment by jondot** [comment]
Version 1.4.3 is out with inflection support.
All you need to do is this:

```
---
to: app/<%= h.inflection.pluralize(name) %>.js
---
hello inflections!
```

**Comment by banyan** [comment]
Super first! 😂😂 Thanks! I'll use it!

**Comment by banyan** [comment]
probably you haven't built yet? there is inflection in `src/context.js` but not `lib/context.js`.

**Comment by jondot** [comment]
Correct! a new build in progress. I'll tell you in a few minutes when it's done

**Comment by jondot** [comment]
Done! you can update to v1.4.5. I've installed and verified everything is OK
