### ISSUE TITLE
Injecting after creating

### ISSUE THREAD

**Issue by epodivilov** [jondot/hygen#304]
I tried to use two templates. In one of them, I create a file, in the other, by condition, I add something to the newly created file. But they seem to be executed in the wrong order and the generator crashes with an error that the file does not exist.

Сan I set the order of execution of templates?

**Comment by mzvast** [comment]
It executes in file list order【aka alphabetical 】.
So you should always put create template first.As shown bellow.
![image](https://user-images.githubusercontent.com/8097465/119091066-14d2d700-ba3f-11eb-8c57-d53a03f7285f.png)

when execute it resolve into actions, as below.
![image](https://user-images.githubusercontent.com/8097465/119091182-421f8500-ba3f-11eb-971d-c8ad8ff3d7a5.png)

**Comment by mzvast** [comment]
I would suggest add an option to touch a empty file if that file is not exist.
![image](https://user-images.githubusercontent.com/8097465/119091854-413b2300-ba40-11eb-80de-419bf9e1b3fd.png)

**Comment by jondot** [comment]
@mzvast is correct, thanks for the answer!
