### ISSUE TITLE
How can I read current `xxx.t` file path?

### ISSUE THREAD

**Issue by Flcwl** [jondot/hygen#323]
I want to the read current `xxx.t` file path and then writting as `to` value.

as follow pic, I hope the env variable `filepath` is current `package.json.t`'s file path: `.templates/create/ui/package.json.t`

![image](https://user-images.githubusercontent.com/26050644/119648297-de88c380-be53-11eb-8f94-a33e265ae57f.png)

**Comment by vaagnavanesyan** [comment]
You can add `index.js` to templates folder as described [here](http://www.hygen.io/docs/generators#advanced-interactive-prompt).  Let's imagine that you have following structure:

|_index.js
|_create
    |_ui
        |_package.json.t

`index.js` can contain exported function which returns plain JavaScript object. Keys of that object would be available in templates as variables. For example you can write the code inside `index.js` which would return something like `{filepath: path.join(__dirname, 'create/ui/package,json.t')}` and it will make variable with name `filepath` with given value available in your templates.

I used this approach a few days ago for some demo for my work. You can use this code as reference:
1. Step 1. Return the object with keys: https://github.com/vaagnavanesyan/generators-demo/blob/master/hygen/_templates/new/entity/index.js#L45
2. Step 2. Use that keys in templates: https://github.com/vaagnavanesyan/generators-demo/blob/master/hygen/_templates/new/entity/inject_reducer.ejs.t#L2

Hope that it would fit your case 🙁

**Comment by jondot** [comment]
Great solution, thanks @vaagnavanesyan
