### ISSUE TITLE
TypeError: string.charAt is not a function

### ISSUE THREAD

**Issue by jcwillox** [jondot/hygen#338]
I'm currently getting type errors when using a name that contains only a single number e.g.
```pwsh
hygen init self 4
```
I believe this is the line that's causing it, it calls the `capitalize` function which in turn calls `string.charAt`. This could probably be fixed by just calling `string = string.toString()` first.
https://github.com/jondot/hygen/blob/94a7ba56dc6c703e76b2c866d2881e9747fc1bb2/src/context.ts#L30
https://github.com/jondot/hygen/blob/94a7ba56dc6c703e76b2c866d2881e9747fc1bb2/src/context.ts#L18-L20

Interestingly adding an underscore postfix, produces the output expected when providing a single number, e.g. creating files named `4.txt` and not `4_.txt`.

```pwsh
hygen generator action 4_
```

**Comment by caiangums** [comment]
Got the same error. But when I start with `0` character, the error seems not to happen.

As an example, use this template project: https://github.com/caiangums/aoc-template and try to run
```sh
yarn solution 01
yarn solution 10
```

The second command triggers the error.
