### ISSUE TITLE
Document predefined locals

### ISSUE THREAD

**Issue by timkelty** [jondot/hygen#34]
There seem to be some predefined locals that can be very useful, e.g. `locals.actionfolder`:

```
`sh: cp -r <%= locals.actionfolder %>/foo <%= cwd %>/`
```

Would be great to get this documented.
/cc @kswedberg

**Comment by jondot** [comment]
Definitely! I'll add that.

**Comment by jondot** [comment]
done!

**Comment by timkelty** [comment]
Wow, thanks for the quickness! 👏
