### ISSUE TITLE
Rename `_templates`?

### ISSUE THREAD

**Issue by yuhr** [jondot/hygen#342]
I usually would love to prefix with `.` than `_` for project configuration files/directories. I'm going to file a PR if you have no opposition to making the directory path configurable.

**Comment by trevor-coleman** [comment]
https://github.com/jondot/hygen/blob/master/src/config-resolver.ts

You can already do this by setting the environment variable `HYGEN_TMPLS`, I think.

**Comment by yuhr** [comment]
It worked, thanks! However, I couldn't notice the environment variable is [documented](http://www.hygen.io/docs/faq#i-want-to-use-generators-from-a-single-place). I think it's reasonable to add another section to the FAQ page, which states “Can I configure path to templates directory?” and “Yes, you can do that by using `HYGEN_TMPLS`” simply.
