### ISSUE TITLE
Advanced prompt documentation improvement

### ISSUE THREAD

**Issue by jaykoontz** [jondot/hygen#35]
Fantastic feature. I ran into a few roadblocks that I eventually overcame myself, so here's a more advanced example in case you find it useful. It covers:
- ensuring all questions are asked before next prompt is executed
- ensuring answers from _both_ prompts are returned (was getting an error for missing template variables if I didn't do this explicitly)
- parsing the first set of answers to create the next set of prompt questions
- accessing dynamically-created variable names in the templates

```
module.exports = {
  prompt: ({ inquirer }) => {
    // defining questions in arrays ensures all questions are asked before next prompt is executed
    const questions = [{
      type: 'input',
      name: 'name',
      message: 'Name of form? (ex: AddContactForm)',
    },
    {
      type: 'confirm',
      name: 'shouldValidateForm',
      message: 'Do you need to validate the form?',
    },
    {
      type: 'input',
      name: 'formFieldNames',
      message: 'Field names? (separate by comma: "field1, field2,field3")',
    }]

    return inquirer
      .prompt(questions)
      .then(answers => {
        const { formFieldNames } = answers
        const questions = []

        // these values can be retrieved in the template with: eval(field + '.validation')
        formFieldNames.split(',').forEach((field) => {
          questions.push({
            type: 'input',
            name: field + '.validation',
            message: `Input the validation for ${field} (ex: isBlank(${field}) && '${field} is required')`,
          })
        })

        // both set of answers must be returned as a merged object, else the previous set of answers won't be available to the templates
        return inquirer.prompt(questions).then(nextAnswers => Object.assign({}, answers, nextAnswers))
      })
  },
}
```

**Comment by jondot** [comment]
Thanks! would you like me to include this example in the docs?

**Comment by jaykoontz** [comment]
It covered a few pitfalls I faced when using the current example, but it is a bit long. Feel free to add it if you think it fits in the docs.

**Comment by jondot** [comment]
Done! added link to this issue and credit 🥇

**Comment by ericwooley** [comment]
Hopefully it's ok for me to add something useful in this thread, since it's already linked too in the documentation. :pray: 

For anyone who gets here looking for an easy way to accept arguments to replace questions, I made a little utility

```js
// I saved this in `_templates/promptArgsUtil.js`

module.exports = questions => ({ prompter, args }) => {
  const providedArgs = questions.reduce((selectedArgs, question) => {
    if (args[question.name]) selectedArgs[question.name] = args[question.name];
    return selectedArgs;
  }, {});
  return prompter
    .prompt(questions.filter(({ name }) => !providedArgs[name]))
    .then(answers => ({ ...answers, ...providedArgs }));
};
```

to use it, import it into your template index.js
```js
//_templates/routes/new/index.js
const promptArgs = require('../../promptArgsUtil')

const questions = [
  {
    type: "select",
    name: "route",
    message: "Select parent route",
    choices: ['.', './routes/route1', 'etc...', 'this is specific to my app']
  },
  {
    type: "input",
    name: "name",
    message: "Name your route"
  }
];
module.exports = {
  prompt: promptArgs(questions)
};
```

Now i can run `hygen route new --name randomThing` and name question will not be asked. or if I leave off the `--name`, the name question will be asked. `hygen route new`

**Comment by hrafnkellbaldurs** [comment]
@ericwooley Thanks for the snippet! Really helpful :smiley:
I noticed one thing which mislead me for a bit, and that's this line here:

`.then(answers => ({ ...answers, ...providedArgs }));`

This is not what provides templates with the provided arguments, they're included anyway.
What I mean by that is that even though you don't add the providedArgs in the returned object, the
arguments are injected into the template, so this ends up doing the same thing:

`.then(answers => answers);`
 
I was trying to format the values in the providedArgs, to make sure all values were valid before being passed to a template, even though it was passed through an argument.
It didn't matter what I did to the returned object, the original arguments always overwrite the end result.

**Comment by ericwooley** [comment]
Cool! glad it was helpful, I haven't mucked with this for a long time, so I'll defer to your judgment on that one.  I'll update the code to reflect your remarks.

**Comment by airtonix** [comment]
updated version of @hrafnkellbaldurs helper: 

```es6
// _templates/Gatherer.js

function Gatherer(questions) {
  return async ({ prompter, args = {} }) => {
    const result = await questions.reduce(async (resultsPromise, question) => {
      const results = await resultsPromise;
      if (args[question.name]) question.initial = args[question.name];

      const answer = await prompter.prompt(question);

      const nestedQuestions =
        typeof question.questions === 'function'
          ? await question.questions({ ...results, ...answer })
          : question.questions;

      const nestedAnswers = Array.isArray(nestedQuestions)
        ? await gather(nestedQuestions)({ prompter, args })
        : {};

      return {
        ...results,
        ...answer,
        ...nestedAnswers,
      };
    }, Promise.resolve({}));
    return result;
  };
}
```

usage: 

`_templates/BasePrompts.js`
```es6
const lodash = require('lodash');

async function PackageName({ prompter, args = {} }) {
  return Gatherer([
    {
      type: 'input',
      name: 'name',
      message: "What's the package name",
      questions: ({ name }) => [
        {
          type: 'input',
          name: 'code',
          initial: lodash.kebabCase(name),
        },
      ],
    },
  ])({ prompter, args });
}

async function PackageMeta({ prompter, args = {} }) {
  return gather([
    {
      type: 'input',
      name: 'package_name',
      message: "What's the module name",
      initial: `@airtonix/${args.code || 'unknown'}`,
    },
  ])({ prompter, args });
}

module.exports = {
  PackageName,
  PackageMeta
}
```

`_templates/tool/new/index.js`
```es6
const { PackageName, PackageMeta } = require('../../BasePrompts');

module.exports = {
  prompt: async ({ prompter, args }) => {
    const packagename = await PackageName({ prompter, args });
    const results = await PackageMeta({
      prompter,
      args: { ...args, ...packagename },
    });

    return results;
  },
};

```
`_templates/tools/new/package.json.ejs.t`
```ejs
---
to: tools/<%= code %>/package.json
---
{
  "name": "<%= package_name %>",
  "version": "0.0.1",
  "private": true
}

```
`_templates/tools/new/provide-root-convenience.ejs.t`
```ejs
---
sh: yarn npe scripts.tool:<%= code %> "yarn workspace <%= package_name %>"
---
```

**Comment by kfern** [comment]
Another option: [Functional approach](https://github.com/kfern/my-vue-monorepo/blob/e93424c94ede85090191165fedc42ca7e6f7ec86/packages/components/lib/inputs.utils.js#L10)

- Each step has a question factory function.
- A function (getInputs) organizes the process and creates the final result
