### ISSUE TITLE
Global variable support?

### ISSUE THREAD

**Issue by querkmachine** [jondot/hygen#358]
Sorry if this is explained in the docs somewhere, I've skimmed though it a couple of times but couldn't see anything.

Does Hygen have support for "global" variables? That is, variables that are defined in one place (e.g. a config file) and are usable in templates?

I'm using Hygen to boilerplate new components in a design system. Because the design system is inheritable, each component is prefixed with a namespace so it's clear which fork of the system introduced and manages that component. If the namespace was "foo" for example: 

```
<div class="foo-component"></div>

.foo-component {}

class FooComponent {}
```

One fork might then change the namespace to "bar" for their new components, another to "baz", etc., allowing "foo-button" and "bar-button" to coexist, if needs be. The namespace typically wouldn't change once set but, ideally, we don't want to have to specify it separately in each template file or in each CLI command. 

In an ideal situation it would be pulled from a configuration file for that fork of the system.

[Alternatively...](https://i.imgur.com/xvTWprF.jpeg)

**Comment by jondot** [comment]
yes, at the most extreme case, you have an escape hatch in `.hygen.js` http://www.hygen.io/docs/extensibility. you can create your own custom utility (`addDesignSystemPrefix(..)` ?) function as well as variables
