### ISSUE TITLE
No "repository" field in package.json

### ISSUE THREAD

**Issue by rand0me** [jondot/hygen#37]
**Problem**:
`npm docs hygen` opens [npmjs.com](https://www.npmjs.com/package/hygen) page and when you click a `documentation` link, you will get 404 error.

There is no "Repository" section in sidebar on  [npmjs.com](https://www.npmjs.com/package/hygen), so you need to g00gle `hygen` (Thanks the name is kinda unique).

A section, I meant, available in this [example](https://www.npmjs.com/package/preact)

Althought, BIG THANKS (and a star, ofc) to you for such a must-have package, an idea of which has been around for years :+1: 

Drop here a comment if this task will be time-consuming (or something else) and I'll send you a PR

**Comment by jondot** [comment]
Thanks for catching this! fixing it right away 😎 
Hope you keep enjoying Hygen, please feel free to jump right in and report anything you like to be added / changed 😸
