### ISSUE TITLE
Hello from kirpichik

### ISSUE THREAD

**Issue by lamartire** [jondot/hygen#39]
Hello, @jondot!
Near half year ago I was inspired and created a little project [kirpichik](https://github.com/lamartire/kirpichik) (it can be not working because it was in development and I changed api and architecture). It's a component generator, based on global installed "templates".

So, main idea was allow to users makes small declarative templates divided on small repositories and packages, but as can I see, your project do the same thing but more simple and elegant :smile: 

If you have any issues and ideas I will be happy to help you, because I really want to solve problem with "routine-written" code and components.

Thank you! :tada:

**Comment by jondot** [comment]
Hello!
Looks great! please feel free to jump in and submit PRs / improvement ideas / anything else, your opinion is very valuable!

**Comment by lamartire** [comment]
Thanks for warm welcome :raised_hands:
