### ISSUE TITLE
hygen doesn't work in 1.5.2 and newer versions

### ISSUE THREAD

**Issue by sse87** [jondot/hygen#40]
I got the same bug as #38 and it seams as it's still a bug in 1.5.7. I have tested installing every version from 1.5.1 to 1.5.7 (latest) and this bug begins showing up in 1.5.2.

It does not matter what command I run, always the same error even when running `hygen init self` or just `hygen` then I get `(node:10480) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Path must be a string. Received undefined`.

I'm using node 6.13.1 installed through nvm-windows on Windows 10.

**Comment by jondot** [comment]
Thanks for taking the time to try and find where's the problem. 
A few questions:

Are you installing globally?
Are you certain what you're running is the 1.5.7 version? (maybe there's multiple installations some where)

To test it in the best way, install locally somewhere through `npm i` without the global flag, and then try `node_mobules/.bin/hygen`

As I'm writing this I'm thinking perhaps this is a Windows specific issue. I don't own a Windows machine anymore, but I'll see if Travis supports CI over it and I'll start there.

**Comment by agung-wete** [comment]
@jondot https://github.com/facebook/jest/issues/3750 maybe ?

**Comment by viktorlarsson** [comment]
Would this help?
https://github.com/jondot/hygen/blob/7743eb9d199f8c79eeec7fc33b11eb844ecc15d5/src/config-resolver.js#L19

      [path.resolve(process.env.HYGEN_TMPLS), path.join(cwd, '_templates')],

**Comment by jondot** [comment]
Thanks @viktorlarsson yes, eventually it was something to do with the path handling differences and the bubbling up algorithm for finding configuration files.
I'm glad to say build passes on Windows, and a new version is now baking in CI!

Thanks all for this group effort!

**Comment by viktorlarsson** [comment]
Deleted my comment, thought I would dig into the code and send a pull request. Glad to see that it sorted itself out! Love the tool :)

**Comment by viktorlarsson** [comment]
@jondot 
I can confirn that it is working on Windows 10 with node 8.9.4.

But is the idea of that functionality that broke it on Windows that you are suppose to be able to have a _templates-folder in your project and it will locate it even if you are in a sub-folder?

**Comment by jondot** [comment]
@viktorlarsson I'm happy to hear!

Regarding `_templates` auto location, initially there was a zero-config workflow that finds `_templates` all along the way up, however it was too much magic: it was disabling the ability to initialize new templates on the way _down_.

So right now what you did is exactly how it should be done, congratz!

**Comment by jondot** [comment]
and happily closing this issue, all: please reopen if needed.
