### ISSUE TITLE
Multiple output

### ISSUE THREAD

**Issue by lamartire** [jondot/hygen#42]
@jondot how about allow to create multiple entities in single line? I think it may be very useful.

User can split `name` value by commas, like `hygen template new --name A,B,C,D`.

I think first variant more suitable, because commas usage in entities names are very strange and rare, as for me.

**Comment by jondot** [comment]
Hi @lamartire!
Currently this is left for the users to do what's best for them.
So then you can get `name` as string and split on `,` or anything else you like. If you find yourself repeating this logic, you can definitely use the new `.hygen.js` mechanism to add custom helpers, see [more here](http://www.hygen.io/extensibility#helpers).
For example you can quickly create a helper that is called `commaSeparatedArray`:

```
commaSeparatedArray: _=>_.split(',')
```

and use it:

```
<% commaSeparatedArray(name).each(n=> { %>
hello <%= n %>
<% } %>
```

**Comment by lamartire** [comment]
Hmm. Does it works with folders or only with one file? I means create multiple folders and files, like you call multiple commands one by one.

**Comment by jondot** [comment]
I think I understand you now!
If I understand correctly you want to run multiple hygen commands using the same parameters.

Hygen does not support out of the box this but you can always use xargs (the Unix tool) to get this behavior.

Hygen supports sub commands out of the box so you can do:

hygen new app:model
hygen new app:controller

And if you want everything in one go you do

hygen new app

Subcommand look at file names so for this to work you have this folder layout:


_templates
  new/
      app/
         controller_one.t
         controller_two.t
         model_foobar.t

**Comment by jondot** [comment]
That would be interesting. I would have hygen read `STDIN`, so:

```
$ cat command.txt | hygen
```

or interactively:

```
$ hygen --
new foobar
new foobaz
^D
```
But I would avoid translating:

```
$ hygen new --name foo,bar,baz
```

To

```
$ hygen new --name foo
$ hygen new --name bar
$ hygen new --name baz
```

Because that would be a surprise to users expecting the string `foo,bar,baz` to pass as-is to the variable `name`.

If you'd like to try to implement this - you're very welcome, and I'll be accepting the PR. Also if you want to think about this a bit more and come up with more ideas - be my guest :)

In general what you're suggesting sounds useful but the challenge is to see how the developer interface turns out

**Comment by lamartire** [comment]
I agree with you about splitting names by commas, but interactive mode can be interesting and perspective in future!
Read from file implies creating files with content for each hygen call, I think it's very extensive for this problem.
Yea, I would think about interactivity mode! :+1:

**Comment by jondot** [comment]
Thanks for bringing this up, please do feel to reopen if you've got new thoughts on this!

**Comment by lamartire** [comment]
Yea, I thinking about this. When I'll do something I'll open PR ;)
