### ISSUE TITLE
Issues triage question -- still under development? 

### ISSUE THREAD

**Issue by JackHowa** [jondot/hygen#425]
Hey I really like this library! And it looks like others do as well given the amount of open issues. I'm curious about the development status on the library and capacity. I even saw another [issue with a company interested](#369) in explicitly funding active development.

In essence, how are maintainers feeling about issue triage? is this repo in a place to start a new project with?

<img width="233" alt="Screenshot 2023-03-27 at 12 15 57 PM" src="https://user-images.githubusercontent.com/5950956/228043828-cfca2226-f530-44ef-bde6-82072931e8d6.png">

**Comment by JackHowa** [comment]
never mind, we're going a different direction -- sorry to bother!

**Comment by tlkiong** [comment]
What is the `different direction`? @JackHowa
