### ISSUE TITLE
Run Hygen without hygen init

### ISSUE THREAD

**Issue by sandalsoft** [jondot/hygen#43]
I'm new to hygen and am loving it so far!  Great work.

I have a use case that is a bit outside the norm, but want to see if it could be handled today or if it's a feature I can help work on.

I want to use hygen as a component/function generator for multiple React and Node projects without running `hygen init` in all of them.  @jondot sort of references this at https://github.com/jondot/hygen/issues/14#issuecomment-365410664, about not being a project generator, so this may be outside the scope of hygen.

I hacked on this a bit with a global .hygen.js in ~ and reference a template tree at ~/.hygen/templates/..., but I get `Error: Cannot find module '[module-name]'` errors if the project I'm in doesn't have those modules installed locally (or globally). 

I know other tools like Yeoman, Plop, etc. can do this, but Hygen is soooo clean and well designed that I would love to use it for my use case.

**Comment by jondot** [comment]
Hi Eric, thanks for the kind words!

You should definitely be able to do this because as you said, the mechanisms for template discovery are simple by design (I just removed a feature that I felt was 'too much magic').

Let's try to do a little deep dive. When you speak of 'those modules' which modules are you referring to?

**Comment by sandalsoft** [comment]
Awesome, thanks!  Any help would be appreciated.

"those modules" == node modules I `npm install`'d to use in my .hygen.js as helpers.

I ran `npm init`and `hygen init` in ~/Development/__node/generator_hygen which is where I'm developing the templates and generators I want to use with other projects.   

**package.json:**
```
{
  "name": "generator_hygen",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "change-case": "^3.0.2",
    "fs-extra": "^5.0.0"
  }
}
```

I have a hygen generator called `function` that creates .js and test.js files in `./src` of the project I'm working on with some boilerplate code from a template, and then modifies the index.js file.

**~/.hygen.js:**
```
const changeCase = require('change-case');

module.exports = {
  helpers: {
    fileCase: (s) => changeCase.paramCase(s)
  }
};

```
When I run `hygen function new --name coolNewFunction` in the project I'm working on, I get this error:
```
(node:84049) UnhandledPromiseRejectionWarning: Error: Cannot find module 'change-case'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/enelson/.hygen.js:1:82)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
(node:84049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:84049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected result:**
- `./src/cool-new-function.js` is created
- `./src/cool-new-function.test.js` is created
- `./src/index.js` is modified to add `export coolNewFunction from './cool-new-function.js'`

**Comment by jondot** [comment]
Hi Eric,
I believe that if you want to have global helpers with a `.hygen.js` file that's at the top of your projects, you want to have modules that its using installed globally. Try installing `change-case` globally (npm i -g) and see if that works.

**Comment by sandalsoft** [comment]
Hi Dotan,

Just tried it, same error :(

**Comment by jondot** [comment]
Tidying up issues (but feel free to reopen if issue persists!)
