### ISSUE TITLE
[Feature Request] Add regexp to (in)validate input with prompt

### ISSUE THREAD

**Issue by MathRobin** [jondot/hygen#44]
Hi,

It could be very useful to be allowed to add a regexp field in prompt to check if typing matches the good format.

For example, i use hygen to generate some elements for angularjs. Some have to be writtent like this "hello-world". It should not start with a number and should contain a dash.

What do you think about this ? Ok if I make a PR about this ?

**Comment by jondot** [comment]
Hi!
I believe prompt.js supports it, look for validation functions.

**Comment by jondot** [comment]
cleaning up. please reopen if relevant
