### ISSUE TITLE
Conditional files

### ISSUE THREAD

**Issue by Lughino** [jondot/hygen#48]
Hi Dotan,
Can I have an example of how to create a file depending to the option passed to the command?
As an example, I would like to create a component structure where if I pass the option `--story` creates also the story file.

Have you a slack channel or similar to have a chat? I'm ok with a github issues, but I don't want to pollute your issues with questions 😀

**Comment by Lughino** [comment]
Never mind! I found it in the documentation!
The question for the slack channel remain open :)

**Comment by jondot** [comment]
Ciao Luca!
I'm happy you found it in the documentation :)
Regarding Slack, there isn't any channel currently just for Hygen, but there might be when I complete the Hyperstack (Hygen is one tool out of many). 

Feel free to pollute Github issues with questions, many times people use it for searching problems so it can be super useful for others 👍
