### ISSUE TITLE
Docs for `with-prompt` are misleading

### ISSUE THREAD

**Issue by wescoder** [jondot/hygen#5]
I was just checking out the docs for the first time and found that the docs are misleading.

Following the instructions does not give the results demonstrated.

hygen generator new --name generatorName - builds a new generator for you
with-prompt new --name generatorName - the same as before, only this one will be prompt driven.

In fact, running `with-prompt new --name generatorName` throws error on the console, because there are no binaries called `with-prompt`.

I couldn't understand what are the docs trying to say here.

**Comment by jondot** [comment]
Very sorry about that, I can definitely see how it can be misleading. Fixing!

**Comment by jondot** [comment]
Done. CI process should push a new website in 3-5min

**Comment by jondot** [comment]
Done! I'll close this issue now.
