### ISSUE TITLE
Stdout not showed

### ISSUE THREAD

**Issue by Lughino** [jondot/hygen#50]
Hi Dotan,
I don't receive the stdout when I launch a command via `sh`.
Just as an example:
```
---
sh: "echo 'hello'"
---
```
I don't see the output produced by this command..
I'm trying to launch a node script with `sh` that return an output.
Any help?
Thank you very much

**Comment by Lughino** [comment]
Ok,
I found out.
I need to change the `exec` option to `runner` adding the `process.stdout` to the pipe:
```javascript
// ....
exec: (action, body) => {
      const opts = body && body.length > 0 ? { input: body } : {};
      const execa = require('execa').shell(action, opts);
      execa.stdout.pipe(process.stdout); // <----- Here
      return execa;
    },
```

**Comment by cannuk** [comment]
Shouldn't this have been added to the project and not just closed?

**Comment by fyyyyy** [comment]
Would be a good default option. Maybe adding hygen --silent would mute stdout

**Comment by yuri-scarbaci-lenio** [comment]
In case others are stumbling upon this on a later date
  not sure if there was a change to execa in some version or what
     but in my case the code from @lughino was not working, 
  
  with very little tweeking I got a working solution on my side
  ```
    exec: (...args) => {
    const [action, body] = args;
    const opts = body && body.length > 0 ? { input: body } : {};
    const execa = require('execa').command(action, { ...opts, shell: true });
    execa.stdout.pipe(process.stdout);
    return execa;
  },
  ```
