### ISSUE TITLE
Cannot use colon (:) character in "skip-if"

### ISSUE THREAD

**Issue by oysmal** [jondot/hygen#53]
There appears to be an issue where the : character cannot be used in "skip-if", even if you escape it using double backslashes. 

Yaml part of generator:
```
to: src/state/entities/entities.reducer.ts
inject: true
skip_if: <%= type.toLowerCase().slice(1) + '\\: ' + type.toLowerCase().slice(1) + 'DefaultState\\,' %>
after: "export const defaultState: IEntityReducerState = \\{"
```

Error message:
```Loaded templates: _templates
YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 3, column 47:
     ... ype.toLowerCase().slice(1) + '\\: ' + type.toLowerCase().slice(1 ...
                                         ^
```

**Comment by jondot** [comment]
Hi! so since this is YAML, it is sensitive to usage of ':'. I recommend wrapping the entire value as a string:

foobar: "any kind of value with : "

**Comment by oysmal** [comment]
Thanks!
I ended up using a different matching string, but will keep this in mind for the future!
