### ISSUE TITLE
if/else condition and loop

### ISSUE THREAD

**Issue by azizasm** [jondot/hygen#55]
How to perform _if else_ condition and  _loop_ using hygen ? 

I'm looking for something like below , can hygen support ? 

if /else:

	#if( $direction < 10 )
	  <strong>Go North</strong>
	#else
	  <strong>Go West</strong>
	#end

Loop

	<ul>
	  #foreach( $product in $allProducts )
		<li>$product</li>
	  #end
	</ul>

**Comment by sibelius** [comment]
I think this is related to template engine used by hygen

it uses `ejs` check `ejs` syntax there

**Comment by jondot** [comment]
Thanks @sibelius!
