### ISSUE TITLE
Expose inflection on prompt callback

### ISSUE THREAD

**Issue by blikblum** [jondot/hygen#59]
In order to provide a default value based on a previous set param, i'm using an external module (camelize) saved on templates folder:

```javascript
const camelize = require('../../_utils/camelize')

module.exports = {
  prompt: ({ inquirer, args }) => {
    return inquirer.prompt([{
      type: 'input',
      name: 'path',
      message: 'Route path:'
    },
    {
      type: 'input',
      name: 'routeName',
      message: 'Route name:',
      default ({path}) {
        return camelize(path, '/') + 'Route'
      }
    }])
  }
}
```

It works fine but has some drawbacks:
* _utils is exposed as a generator
* this could be accomplished with inflection without resorting to custom code

I could install inflection in project but seems overkill. 

If inflection is injected into prompt callback we could reuse it. Something like:

```javascript
module.exports = {
  prompt: ({ inquirer, args, inflection }) => {
    return inquirer.prompt([{
      type: 'input',
      name: 'path',
      message: 'Route path:'
    },
    {
      type: 'input',
      name: 'routeName',
      message: 'Route name:',
      default ({path}) {
        return inflection.camelize(path.replace('/', '_')) + 'Route'
      }
    }])
  }
}
```

**Comment by jondot** [comment]
Closing because this was done :heart:

**Comment by blikblum** [comment]
> Closing because this was done ❤️

Sorry for reopening so later

But how i can access inflection (h helpers) in prompt file?

Just tested and the only params being passed to prompt hook is prompter and args as can be observed in this code: https://github.com/jondot/hygen/blob/0d0b1b08dc6eed89a11ac90d2b74714887b8182e/src/prompt.ts#L30
