### ISSUE TITLE
Better docs for prompt

### ISSUE THREAD

**Issue by wescoder** [jondot/hygen#6]
https://github.com/jondot/hygen/blob/79358a6dfcda33ff2d947304d1f67698f9c53716/src/templates/init/self/new-generator-with-prompt.prompt.ejs.t#L9

Wouldn't be better to link to [this docs](https://github.com/SBoudrias/Inquirer.js#prompt-types), since they actually show which types of questions can be used?

The actual link drops into a list of files showcasing how to implement Inquire.js API, but hygen just expose access to [Question objects](https://github.com/SBoudrias/Inquirer.js#objects), so users could get lost if they click [bottom-bar.js](https://github.com/SBoudrias/Inquirer.js/blob/master/examples/bottom-bar.js) for example.

**Comment by jondot** [comment]
oh definitely. keep this feedback coming, great stuff!

**Comment by jondot** [comment]
Done! CI should push a new build to NPM in a few minutes
