### ISSUE TITLE
Logging info is being show when running generator

### ISSUE THREAD

**Issue by blikblum** [jondot/hygen#60]
When running a generator some logging info is being show:

> hygen view new
? Scope: global
? View name: PersonXView

Loaded templates: D:\repositories\endocrinassist\webclient/_templates
       added: D:\repositories\endocrinassist\webclient/src/common/views/person-x.js
results [ { type: 'add',
    subject: 'D:\\repositories\\endocrinassist\\webclient/src/common/views/person-x.js',
    status: 'added',
    timing: 0 } ]

**Comment by blikblum** [comment]
This seems to be the culprit: https://github.com/jondot/hygen/blob/3de56c28d5eee4a74b6e0a1827292ff666d53ae7/src/execute.js#L28

**Comment by jondot** [comment]
ouch! good catch, thanks!
