### ISSUE TITLE
Provide way to define variable to be used in frontmatter

### ISSUE THREAD

**Issue by blikblum** [jondot/hygen#61]
I have the following frontmatter:

```
---
to: "<%= fileScope === 'global' ? h.rootDir() + '/src/common/views/' + h.inflection.transform(name, ['underscore', 'dasherize']).replace('-view', '') : h.inflection.transform(name, ['underscore', 'dasherize'])%>.js"
---
```

The `h.inflection.transform(name, ['underscore', 'dasherize'])` is being used twice making code harder to read

I could not find a way to declare a variable to be used in the frontmatter like can be done in template body.

I tried
```
---
dashName: <%= h.inflection.transform(name, ['underscore', 'dasherize']) %>
to: "<%= fileScope === 'global' ? h.rootDir() + '/src/common/views/' + dashName.replace('-view', '') : dashName %>.js"
---
```

But it gives an error dashName not defined

**Comment by CharlesBradshaw** [comment]
I have a similar issue, I'm trying to allow for short hand parameters so a user could type "path" or "p", at the top of my file (above the front matter) I try to run 
```
<%
  if(typeof path == 'undefined'){
    var path = typeof p == 'undefined'?'':p
  }
%>
---
to: helloworld.js
---
console.log("hello")
```

but when I run the generator, it doesn't create any files and prints in the terminal "loaded templates _templates"

My current workaround is to move the code between the to: and the path like so
---
to:<%
  if(typeof path == 'undefined'){
    var path = typeof p == 'undefined'?'':p
  }%>helloworld.js
---
which would be okay, but the variables don't transfer between templates, and in reality I have 4 parameters so I would end up having to copy 20 lines of preprocessing to each template

Assuming doing preprocessing at the top of the file isn't possible, I think the best solution would somehow allow passing a (memoized) preprocessing function to the frontmatter that is given an object of the parameters and returns an object of processed parameters where each key would be set as a variable in the template's this scope.

For example if a preprocessing function returned the following
`{path:'/hello/world/'}`

we could loop over the object and set the this like so
`this[key] = val`

**Comment by ezhikov** [comment]
Hello. I have an idea how to make this pretty painless. Mind if I take this? Probably I would need help with tests, since I have very little experience in testing things.

**Comment by jondot** [comment]
Hi guys, and @ezhikov thanks for taking the initiative to build in support for this. Before we move forward - did you try to check the `.hygen.js` file?
For the cases you want cross-template facilities (variables, helpers), this is where extensibility goes.

Let me know if you need help with that approach

**Comment by ezhikov** [comment]
Thank you. I'll look closer in few days.

**Comment by blikblum** [comment]
>  Before we move forward - did you try to check the .hygen.js file?

The problem with this approach is that, in the example i posted, i would not have access to `h.inflection.*` functions, i would need to add as a dependency to each of the projects that use this generator.

What would work is if a function is to pass all builtin helpers as an argument if hygen.js returns a function:

```javascript
//.hygen.js
return function (h) {
  return {
     dashName(name) {
           return h.inflection.transform(name, ['underscore', 'dasherize']
     }
  }
}
```

**Comment by lastobelus** [comment]
It's not just frontmatter, but also DRYing between multiple templates in a generator.

To my mind the most flexible solution would be for hygen to look for a file called `context.js` which exports an object in the generator and add it to the context for all templates in the generator as `context` or some other name. 

Optionally, it could call `init(locals)` if that function exists, to make initializing easier.

**Comment by jondot** [comment]
@blikblum amazing feedback - looks like with your feedback we can uncover something that's very easy to do - adding those helpers to .hygen.js!
@lastobelus yup! that would be the purpose of .hygen.js (unless you see something I missed?)

**Comment by anithri** [comment]
This also works
```
---
to: /tmp/testMeVar.txt
arbitrary: <% changed = Name + '!!!' %>
---
<%= changed %>
```

**Comment by eightyfive** [comment]
Thanks @anithri 

```js
// generator/action/index.js
const s = require('inflection');

module.exports = {
  params: ({ args }) => {
    const names = s.pluralize(args.name);

    return {
      names,
      Names: s.capitalize(names),
    };
  },
};
```

@jondot It would be nice to have access to the `name` variable in the `params` method. Meanwhile I am obliged to call my generator "the old way":

```
$ hygen generator action --name=foo
```
Instead of the new / cleaner way:
```
$ hygen generator action foo
```

**Comment by scramblor** [comment]
The one issue I have with using .hygen.js is the code becomes a bit more verbose. ie. `h.transformer(originalArg)` vs `transformedArg`.

Ideally I would like to be able to combine the prompter with params in index.js so that the params function can add extra members or do transforms with the output of prompter. There are a few good ideas floating around though.

Also took me a fair bit of time to realize that the prompter is ignored if params is present. This should be an error or at least a warning. Also maybe the documentation can be a bit clearer that these are mutually exclusive.

**Comment by jondot** [comment]
closing because this was done :heart:
