### ISSUE TITLE
skip_if without inject

### ISSUE THREAD

**Issue by cemkalyoncu** [jondot/hygen#67]
What the title says, but if you want to hear why, keep reading.

First off, incredible tool, saved me hours of work. What I needed was not supported by any other generator. My workflow is quite different than what hygen offers, but it is flexible enough to fit in. 

What I do is to generate web application modules. Basically, it allows add, modify, list, search and many more functionality for a database table. However, these modules require changes along the way. Also making mistakes during data entry is quite possible. Imagine answering 100 questions regarding to 10 or more fields. So what I did was to save the generator data in json, and if the same module name is used again, it simple loads up existing data and allows you to modify it. 

This system work great; however, there are times when the module files needs to be customized beyond what the generator script is capable of doing. In these cases, it would be very good to have a marker in the file so that the generator will not replace it. I know I can skip manually but remember each page with modification in a project involving many modules is not feasible. skip_if working in regular files will make this usage possible.

**Comment by jondot** [comment]
Hi, would love to support the feature you're describing but I'm afraid I don't fully understand what you're trying to accomplish.
A github repo with sample would be perfect. We can also try hangouts/Zoom (although might be tricky to find times in terms of timezone etc.).
Would any of that work?

**Comment by jondot** [comment]
Cleaning up -- please feel free to reopen if needed 👍
