### ISSUE TITLE
Can't pass variable into conditional "to" in frontmatter

### ISSUE THREAD

**Issue by covertbert** [jondot/hygen#70]
If I try this:

`to: "<%= container ? /some/path : null %>"`

it works fine, but this:

`to: "<%= container ? <%=  path %> : null %>"`

does not work. Am I doing something wrong here or is this not supported?

**Comment by covertbert** [comment]
Ahh that makes sense, cheers mate!

**Comment by znamilya** [comment]
How to be with this case:
`to: "<% locals.extra.includes('with-api') ? 'src/store/collections/<%= name %>/api.js' : null %>"`
