### ISSUE TITLE
Empty line on top genarated injection

### ISSUE THREAD

**Issue by bernessco** [jondot/hygen#75]
I can't find any documentation about removing top line (not last with eof_last). Is this just a missing feature?

**Comment by jondot** [comment]
Might be a missing feature. Could you provide a working example to demonstrate? (alternatively, feel free to take a look at the inject tests - there should be examples of injects and what they do to content)

**Comment by bernessco** [comment]
I'm trying to inject imports to file before export, but by default injection adds empty line at top.

```
---
inject: true
to: src/state/index.js
before: "export default {"
skip_if: <%= h.inflection.camelize(name) %>
eof_last: false
---
import <%= h.inflection.camelize(name) %> from './modules/<%= h.inflection.camelize(name) %>'

```
Before: 
```
import App from './modules/App'
export default {
}

```

Outupt: 

```
import App from './modules/App'

import Auth from './modules/Auth'
export default {
}
```

**Comment by jondot** [comment]
ah! I think this happened to me as well, because VSCode kept inserting a new line in the original template. Try to double-check that you don't have a newline in your template file

**Comment by bernessco** [comment]
It adds only last line, but maybe it has something to do with CRLF?

**Comment by jondot** [comment]
@bernessco might be - on which OS are you on?

**Comment by bernessco** [comment]
@jondot macOS Mojave 10.14.2
### .editorconfig
```
[*]
charset = utf-8
indent_style = tab
indent_size = 4
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by gnomeria** [comment]
It keeps happening to me. What's the workaround or has the fix been made? Thanks

**Comment by jondot** [comment]
I believe this should be gone by now, I've upgraded front-matter, which I think was the source of this.
Please reopen if in v6.x it keeps happening (to be released later today)

**Comment by yassinebridi** [comment]
I think this is still happening, version 6.0.4.
I'm using vim, yet @fcbajao solution is not working.
Using Arch linux, linux: 5.11.12-arch1-1

**Comment by amaro0** [comment]
I had similar problem and writing regex so it matches empty line before export helps.

Try `before: ^\sexport default`
