### ISSUE TITLE
Using eslint to lint template files

### ISSUE THREAD

**Issue by shajith** [jondot/hygen#77]
Thank you for Hygen!

I needed to run eslint over the `.ejs.t` files I'm checking in with a generator. Is there a way to do that? 

There is an `eslint-plugin-ejs` plugin that should takes care of parsing out the ejs placeholders, but eslint is getting tripped up on the `---` sections at the top with errors like:

```
  1:3  error  Parsing error: Invalid left-hand side in prefix operation

> 1 | ---
    |   ^
  2 | to: _templates/<%= name %>/<%= action || 'new' %>/prompt.js
  3 | ---
  4 | 
```

Any ideas on how to do this right?

**Comment by rhberro** [comment]
Is there any special reason to run eslint over your template files instead of the generated ones? Hygen has an especial kind of template files that let you [run any shell command](http://www.hygen.io/templates#shell) from it, try using it with the eslint `--fix` option.

**Comment by jondot** [comment]
@shajith I wish there were, I just pick the `t` suffix to avoid any editor linting tools. But if there's an editor that _understand_ YAML frontmatter and ejs combined that I guess it would work. I didn't find any yet.

**Comment by shajith** [comment]
@rhberro I was trying to verify that the templates I'm adding to the project don't include linting errors themselves. I've been doing a test generation and eslint run manually now, and wanted to automate that so it can be rolled into our general eslint run on CI. Thanks for the `sh` recommendation, I'll explore that.

@jondot: It seems like we need a variant of the `eslint-plugin-ejs` library that is aware of hygen front-matter. Thanks for that context, will dig further.

**Comment by jondot** [comment]
Thanks guys, cleaning up issues -- please feel free to reopen if needed 👍
