### ISSUE TITLE
generate multiples files and folders

### ISSUE THREAD

**Issue by sibelius** [jondot/hygen#79]
I have a monorepo project using lerna, and I'd like to generate a group of files and folder when I want to create a new package

is this possible?

the final output would be something like this:

```
<package-name>
- src/index.js
- package.json (name: '<package-name>')
- eslintrc.js
- babel.config.js
```

**Comment by jondot** [comment]
yes, it's possible -- you can generate any folder structure you want without any limit imposed by name of generator, name of template etc.

**Comment by sibelius** [comment]
is there an example of doing this?

One command to generate many files and folders?

**Comment by jondot** [comment]
Yes I’ll find one for you in a bit

**Comment by jondot** [comment]
This example shows how to generate multiple files (which go into and create if needed folders) https://github.com/jondot/hygen/tree/master/src/__tests__/metaverse/hygen-templates/_templates/mailer/new

let me know if that helps

**Comment by sibelius** [comment]
it works great, I was thinking about folder creation, but Hygen manages this by itself already.

You can have this structure:

_templates
-- package
---- new
------ index.ts.t
------ babel.config.js.t
------ prompt.js

-------

index.ts.ts
```ejs
--
to: packages/<%=package%>/src/index.ts
--
// TODO - add package content here
```

and so on

maybe we can have a section on docs about generating multiple files

**Comment by jondot** [comment]
yep. I must admit when building Hygen I made sure to build things generically and give a little bit more power than I needed -- so I love to be surprised when people use it in unexpected ways to get the job done :) 

I would happily accept a PR for documenting this (I imagine Q&A would be the easiest to just go ahead and write about it) 👍
