### ISSUE TITLE
License link in README points to a missing file

### ISSUE THREAD

**Issue by Calinou** [jondot/hygen#8]
The [link to the LICENSE file](https://github.com/jondot/hygen/blob/master/LICENSE.txt) contained in the README points to a missing file in the repository.

**Comment by EstebanBorai** [comment]
Hey! Looks like the LICENSE is not in the directory, maybe you missed it?

**Comment by jondot** [comment]
Thanks for the tip just pushed the missing file. License is MIT - so no worries.
