### ISSUE TITLE
Wrong capitalizing in [y/n] question

### ISSUE THREAD

**Issue by michaeljohansen** [jondot/hygen#83]
While running **`hygen some-gen new --name some-name`** with **`unless_exists: false`** I get a conflicting message in the [y/n] prompt. First [y/N], then [Y/n].

![image](https://user-images.githubusercontent.com/582580/49249795-793bef00-f41d-11e8-8aa3-d73bd761af6a.png)

**Comment by jondot** [comment]
Interesting! adding this to be checked!

**Comment by jondot** [comment]
Thanks -- this should be resolved now since we moved to a different prompter
