### ISSUE TITLE
Provide Windows releases in a resonable format

### ISSUE THREAD

**Issue by schotlandzegtja** [jondot/hygen#86]
Hey!

Releasing Windows binaries in a tarball raises the barrier to entry and will put off users (like my colleagues). It means that the pre-requisite for Hygen is 7zip or similar, which is wholely unnecessary.

Can the Windows binaries be published as zipfiles, as is the case for just about every other project with Windows releases?

Thanks!

Ross

**Comment by jondot** [comment]
Hi! It shouldn't be a problem. Having not used windows for the last 8 years I figured it wouldn't matter by now -- note taken!

**Comment by schotlandzegtja** [comment]
@jondot Thanks for such a quick response 👍 and thank you for Hygen!!!

**Comment by jondot** [comment]
Should be good now! thanks for the feedback 👍
