### ISSUE TITLE
Running global generators without needing to `hygen init self`

### ISSUE THREAD

**Issue by DeX3** [jondot/hygen#89]
Hey there,

would be kind of nice to be able to run global generators without needing to run `hygen init self` (for example to bootstrap entire projects).

From reading the source, I saw that there's a way to configure a template directory via `.hygen.js` or the `HYGEN_TMPLS` environment variable. However, hygen still expects `init self` to have been run.

Are there any plans to make this work without having to do `hygen init self`?

**Comment by jondot** [comment]
Hi
Thanks for the feedback, from my tests, Hygen doesn't need an `init` if supplied with such a folder:

```
~/experiments
❯ HYGEN_TMPLS=~/experiments/hygenexp/_templates hygen

Error: please specify a generator.

Available actions:
generator: help, new, with-prompt
```

(also just verified with using a .hygen.js file)

Closing this for cleanup purposes, but feel free to reopen if for some reason you can find a reproducing example.

**Comment by DeX3** [comment]
Yeah, sorry about that - I got it working too.
