### ISSUE TITLE
hygen@1.6.4 not published

### ISSUE THREAD

**Issue by Stevo14850** [jondot/hygen#90]
Hello!

The `1.6.4` version of hygen is not published to npm right now, current `latest` is `1.6.2`.

Noticed this when trying to use `changeCase` functionality as described in the docs but `changeCase` is not available in `1.6.2`.

**Comment by jondot** [comment]
Hi!
Sorry about the delay, Hygen 2.0.1 is now cooking in the CI pipeline, will be released automatically in a few minutes.
This version incorporates the change you need as well as a major performance improvement - we dropped inquirer in favor of enquirer (the prompt interface changes a bit, but if you didnt use prompts you have no breaking changes and can enjoy the boost in speed).

**Comment by codeninja-ru** [comment]
Please find time to publish the new version to npm.

I found your wonderful product recently and tried to do h.changeCase.paramCase as it was said in the doc and it was not working.

**Comment by jondot** [comment]
all - thanks for helping out. hygen 2.0.3 is now released to npm.
it turned out to be a problem with npm authentication, but the job hadn't failed to indicate it
