### ISSUE TITLE
Question: is it possible to have async helpers?

### ISSUE THREAD

**Issue by oscarnevarezleal** [jondot/hygen#95]
I extract the following from the docs. 

_Note that beyond inlining a utility function like in this example, you can require and use any piece of code in your project here and export it for Hygen to use._
```
module.exports = {
    helpers: {
        extended: s => s.toUpperCase()
    }
}
```
Seems like _extended_ expected to have a return value, how could I create an async helper?

**Comment by oscarnevarezleal** [comment]
It seems that is not possible at the moment because EJS has no support for it. The workaround I found was to pipe a generator's output into a shell command as described here http://www.hygen.io/templates#shell

**Comment by jondot** [comment]
Thanks @oscarnevarezleal that's a good workaround, shell command is a joker card that can be very powerful (from running custom node/python/shell scripts).

Can you share the specific use case you're dealing with so we can learn from it? i imagine something like loading data from an external JSON API maybe?

**Comment by oscarnevarezleal** [comment]
Hi @jondot, exactly right. I´m building a template which fetches _partials_ from a remote source. There are sometimes when you need to include a piece of code that lives outside your project.

**Comment by jondot** [comment]
I will add a ticket for feature request, to support async helpers.
