### ISSUE TITLE
Best Practice for variable casing

### ISSUE THREAD

**Issue by gaharrington** [jondot/hygen#97]
Here is my hygen call:
`hygen new-cloud-function new --name createTestWidget`

I would like to insert two versions:
`createTestWidget` and `CreateTestWidget`

What is the best way to handle this? I have tried:
`import { <%= Name %> } from './<%= name %>'`

But I end up with an incorrect output:
`import { Createtestwidget } from './createTestWidget'`

Desired output:
`import { CreateTestWidget } from './createTestWidget'`

UPDATE:
This gives the desired output:
`import { <%= h.inflection.camelize(name) %> } from './<%= h.inflection.camelize(name, true) %>'`

NEW QUESTION: Is there a less verbose way to do this?

P.S. Is this an appropriate place for this question? I looked for a Hygen Slack channel, but I did not find anything.

**Comment by jondot** [comment]
Hi @gaharrington yes that is the correct way to do it. I'm sorry there isn't a shorter version but you can always make your own `.hygen.js` file, which serves as global utilities -- in which you can create shorthand functions to any thing you'd like.
